### ISSUE TITLE
[Request] MyPet support

### ISSUE THREAD

**Issue by promorrom** [GC-spigot/AdvancedSpawners#1]
Be able to leash these pets in MyPet.
So they could attack players and be attacked.
I know this will be hard, but I'm not sure if I read that the Custom Mobs from Advanced Spawners currently use the AI of the silverfish or something like that, so it would not be hard to implement the Pet vs environment or pet vs player.

**Comment by GC-spigot** [comment]
Pets will be coming down the road.
