### ISSUE TITLE
[Issue] Bentobox support

### ISSUE THREAD

**Issue by Bricec6** [GC-spigot/AdvancedSpawners#101]
**Describe the bug**
When I put down spawneurs, and break them, bentobox will always take into account that there are spawneurs on the island. (except it doesn't do that problem with another spawneur plugin.)

**Screenshots / Video**
I put a total of 4 spawneur, because my island is limited to 4 spawneur.
![image](https://user-images.githubusercontent.com/51750055/85407398-73f44700-b563-11ea-8a21-a367db6f41d9.png)

I break all four spawneurs in gamemode 0.
![image](https://user-images.githubusercontent.com/51750055/85407497-92f2d900-b563-11ea-8b3e-6adc4ca71845.png)

I'm trying to rest the spawneurs, and he thinks I still have four spawneurs on my island.
![image](https://user-images.githubusercontent.com/51750055/85407582-aaca5d00-b563-11ea-818c-33b93c8ba8e6.png)

**Server Information (please complete the following information):**
 - Paper 350 (1.15.2)
- AdvancedSpawners-2.2.3

**Comment by GC-spigot** [comment]
This isn’t a problem on my end but your island plugin - needs to add support for my plugin

**Comment by Bricec6** [comment]
i request it

**Comment by Bricec6** [comment]
iit's good?
