### ISSUE TITLE
[Issue] Configuration 

### ISSUE THREAD

**Issue by LeCraft2Ouf** [GC-spigot/AdvancedSpawners#102]
**Describe the bug**

Hello, each time the plugin is reloaded, the configuration files will reset

In addition, I reload once said "Loaded 33 mobs configuration" I repeat once said "Loaded 44 mobs configuration" again its said 55 then 66 ect, it adds 11 to each reload

Version plugin Latest
Version paper 1.15
2 latest

**Comment by GC-spigot** [comment]
Fixed
