### ISSUE TITLE
Problems with placing or taking spawners from stacking gui.

### ISSUE THREAD

**Issue by magiciangoh** [GC-spigot/AdvancedSpawners#103]
**Describe the bug**
Placing multiple spawners using the gui doesnt increase the spawner numbers, it only takes away to spawner from hands. However, placing the spawners one by one on the ground works fine.

**To Reproduce**
A way to reproduce the video

**Screenshots / Video**

**Server Information (please complete the following information):**
- Paper 1.15.2
- 2.2.2

**Comment by GC-spigot** [comment]
Fixed
