### ISSUE TITLE
[Issue] loadedclass

### ISSUE THREAD

**Issue by Bricec6** [GC-spigot/AdvancedSpawners#104]
**Describe the bug**
Message in chat, on plugin load

![image](https://user-images.githubusercontent.com/51750055/85471007-205c1a80-b5b0-11ea-8ce3-cfee803b2e2d.png)

![image](https://user-images.githubusercontent.com/51750055/85471030-27832880-b5b0-11ea-8091-dacd7a28359b.png)

**Server Information (please complete the following information):**
 - Minecraft Version paper 353
- Plugin Version AdvancedSpawners-2.2.4

**Comment by GC-spigot** [comment]
Can't be fixed at the moment sadly, looking into it still

**Comment by Bricec6** [comment]
you do have do, so I don't think there's any point in closing the ticket...
