### ISSUE TITLE
[Issue] Hologram on all mobs on my server

### ISSUE THREAD

**Issue by Bricec6** [GC-spigot/AdvancedSpawners#105]
**Describe the bug**
Hello your plugin adds holograms to all my server monsters! 
can you add a condition that if it's stacked and comes out of a spawner then there will be a hologram? like: https://github.com/GC-spigot/AdvancedSpawners/issues/100
Because of that, your plugin acts on mythicmobs...

**Screenshots / Video**

![image](https://user-images.githubusercontent.com/51750055/85471412-b7c16d80-b5b0-11ea-8b92-ed37654c72de.png)

**Server Information (please complete the following information):**
 - Minecraft Version paper 353
- Plugin Version AdvancedSpawners-2.2.4

**Comment by GC-spigot** [comment]
You can change this by changing config values:
https://prnt.sc/t5ratu
Add spawning causes https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html from here all except for SPAWNER
