### ISSUE TITLE
stackmob problem

### ISSUE THREAD

**Issue by Unspecified13** [GC-spigot/AdvancedSpawners#11]
**Describe the bug**
whe see 2 placeholder off how many mob is stack and for exemple it's right 3 and 6 so we need to have 9 mobs but no we have just 3 mob 
**To Reproduce**
A way to reproduce the video

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/62668152/77573522-13f0f480-6ed1-11ea-9fe0-54b07563f632.png)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 1.20

**Comment by GC-spigot** [comment]
Fixed
