### ISSUE TITLE
Spawner Duplication Glitch

### ISSUE THREAD

**Issue by SkyblockinDev** [GC-spigot/AdvancedSpawners#112]
**Describe the bug**
When a user placed down a spawner and then places down another 15 spawners into the stack, creating the stack amount of 16, the user can then go the break/place multiple parts with on the GUI when you right-click the spawner and then click on the break 16. it will add 16 spawners to you inventory however will still leave 1 spawner on the ground that you can then mine and gain an extra spawner so you original 16 is now 17. (This happens for 64 and 32)

You just need to change it so that there needs to be 17 in the stack to break 16, 33 to break 32 and 65 to break 64

**To Reproduce**
A way to reproduce the video

**Screenshots / Video**
https://gyazo.com/171298bc5fa8ed81ed7ca65d6cec9b88

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSigot 1.8.8
- Plugin Version: 2.2.4

**Comment by GC-spigot** [comment]
Fixed
