### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by MagnusMelbye** [GC-spigot/AdvancedSpawners#114]
The default drops of a blaze is blocked. When a blaze is killed, by a player or something else it only drops exp.
I'll suggest taking a closer look at the mobs, since there are issues with blazes, slimes and magma cube, as i also pointed out in a earlier thread.
Minecraft Version [Paperspigot 1.15.2]
Plugin Version [2.2.2]

**Comment by GC-spigot** [comment]
Resolved
