### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Tomigames** [GC-spigot/AdvancedSpawners#115]
**Describe the bug**
I am running into the following issue with the plugin Shopkeeper and AdvancedSpawners they are both running on a server bellow I have attached a video and a Paste with the console errors that AdbancedSpawners is causing.
https://paste.md-5.net/usacazumef.md

**To Reproduce**
https://www.youtube.com/watch?v=hQaXL9xrlN8&feature=emb_logo

**Screenshots / Video**
https://www.youtube.com/watch?v=hQaXL9xrlN8&feature=emb_logo

**Server Information (please complete the following information):**
 -  PaperSpigot 1.814.4
-  Plugin ver 2.2.6

**Comment by GC-spigot** [comment]
I have no idea why you'd think both are related, issue is not related to shopkeeper plugin and just tab completion - fixed.

**Comment by Tomigames** [comment]
That is not the case. Your plugin is causing mobs and other plugins that interact with mobs not to work correctly. This can be seen when a shopkeeper is spawned. 

When your plugin is on more than 1 villager apear
When your plugin is off only one villager apears.
