### ISSUE TITLE
advangedspawmer bypass the flags in bskyblock

### ISSUE THREAD

**Issue by makemp1997** [GC-spigot/AdvancedSpawners#118]
**Describe the bug**
Visitors can kill or destroy armor stands from others

**To Reproduce**
1. place asdvangespawmer in an bentobox / bskyblock
2. A  player visit anothers players island
3. That player kill an animal, or destroy an animal stand

**Screenshots / Video**
Well this is a report my players, so I do not sadly a video, also tested it removing advangesspawmer

**Server Information (please complete the following information):**
 - Minecraft Version paper 1.15.2 
- Plugin Version 2.2.2
Wel I have did before this already about the same issue a report, https://github.com/GC-spigot/AdvancedSpawners/issues/62
But sadly the issue is still here, although I found that that AdvancedSpawners will ignore the flag fron bskyblock.
So wouldn't it be possible to make bentobox softdepended in AdvancedSpawners, so it will respect the flag in bskyblock.

**Comment by Bricec6** [comment]
https://github.com/GC-spigot/AdvancedSpawners/issues/101

**Comment by makemp1997** [comment]
Hello,
Well after removing the advangedspamner as a test from, my server, the issue have been resolved so imo it is not just an bentobox issue.

**Comment by makemp1997** [comment]
Hello,

Wel since I got some issues with this plugin in Skyblock, so added in survival although sadly there I found out it wasn't bypassing bentobox also it was bypassing worldguard as well. See https://youtu.be/2p0H4KP2zBI.

For your info:

- Gamemode / server: Survival
- version: 
![Survival version](https://user-images.githubusercontent.com/22965328/90310037-1094ee80-deee-11ea-9110-fc94ca5f4cb1.png)
- plugins: 
![Survival plugins](https://user-images.githubusercontent.com/22965328/90310046-1985c000-deee-11ea-8bf2-f096e8f7c7d8.png)

So I hope that you can fix this.

Greetings,

makemp2014
aka makemp1997
