### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Telrdonttell** [GC-spigot/AdvancedSpawners#119]
**Describe the bug**
When picking the option to break a spawner through the GUI it gives you a spawner and doesn't break the spawner placed, also non-opped players can't silk touch spawners
**To Reproduce**
A way to reproduce the video

**Screenshots / Video**
https://gyazo.com/6b3879289862cbb5520cc3b29613ee3d
![SpawnerGUi](https://user-images.githubusercontent.com/67659965/86176869-e1afee00-bae2-11ea-8af6-f8b452382f7b.PNG)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 6.7.8]
Minecraft: 1.15.2
Plugin Version: 2.2.5

**Comment by Telrdonttell** [comment]
Gyazo is a video example ^

**Comment by GC-spigot** [comment]
Got any other spawner plugins?

**Comment by GC-spigot** [comment]
Non-opped players need the permission for silktouch `advancedspawners.silktouch`, everything else seems to be fixed
