### ISSUE TITLE
[Issue] with entities

### ISSUE THREAD

**Issue by Tomigames** [GC-spigot/AdvancedSpawners#120]
Describe the bug
I am running into the following issue with the plugin Shopkeeper and AdvancedSpawners they are both running on a server bellow I have attached a video and a Paste with the console errors that AdbancedSpawners is causing.
https://paste.md-5.net/usacazumef.md

To Reproduce
https://www.youtube.com/watch?v=hQaXL9xrlN8&feature=emb_logo

Screenshots / Video
https://www.youtube.com/watch?v=hQaXL9xrlN8&feature=emb_logo

Server Information (please complete the following information):

PaperSpigot 1.814.4
Plugin ver 2.2.6

That is not the case. Your plugin is causing mobs and other plugins that interact with mobs not to work correctly. This can be seen when a shopkeeper is spawned.

When your plugin is on more than 1 villager apear
When your plugin is off only one villager apears.

**Comment by Tomigames** [comment]
Plugin ver 2.2.7 still happening

**Comment by GC-spigot** [comment]
Go into config.yml and change `stackingBlacklist` to include the mobs you want

**Comment by Tomigames** [comment]
I streight up have stacking off.
