### ISSUE TITLE
[Issue] Commande /as drops

### ISSUE THREAD

**Issue by LeCraft2Ouf** [GC-spigot/AdvancedSpawners#122]
**Describe the bug**
I don't have access to the /as drops command anymore, I thought it was because my configuration was obsolete but even after I deleted the folder and restarted the server I still get this error, so nothing opens. 

[latest.log](https://github.com/GC-spigot/AdvancedSpawners/files/4874158/latest.log)

**Server Information (please complete the following information):**
 - Minecraft VersionPaperSpigot 1.15.2 Latest
- Plugin Version Latest

**Comment by GC-spigot** [comment]
Fixed
