### ISSUE TITLE
[Request] Compatibility Skript

### ISSUE THREAD

**Issue by LeCraft2Ouf** [GC-spigot/AdvancedSpawners#123]
Hello,

My zone protection system being developed with the Skript plugin. I cannot protect your spawners from breakage.

The "On break:" event is not detected when one of your spawners is broken. So I can't cancel event, if it doesn't belong to the player.

It would be really cool to integrate compatibility with the Skript plugin, because I'm annoyed because players can break spawners even in areas claimed by other players ( 
Claim Plugin made with Skript )

Yours sincerely,

**Comment by GC-spigot** [comment]
I don't believe this can be implemented with Skript, there is an API for Java
