### ISSUE TITLE
[Issue] Lava bug

### ISSUE THREAD

**Issue by LeCraft2Ouf** [GC-spigot/AdvancedSpawners#125]
**Describe the bug**
Hello, one of my players sent me this bug. As you can see on the video, the silverfish (Robot) dies slowly with the lava. But when the silverfish dies all the robots dispawn without dropping anything. Which is a shame

**Screenshots / Video**
https://youtu.be/ECu4NNppQhs

**Server Information (please complete the following information):**
 - Minecraft Version Paper 1.15.2 Latest
- Plugin Version Latest

**Comment by GC-spigot** [comment]
Fixed
