### ISSUE TITLE
[Issue] Mob vanilla does not spawn

### ISSUE THREAD

**Issue by LeCraft2Ouf** [GC-spigot/AdvancedSpawners#126]
**Describe the bug**
Hello, I noticed that not all vanilla mobs spawn with your spawners, only your mobs create who spawner

**Server Information (please complete the following information):**
 - Minecraft version Paper Spigot Latest
- Plugin Version Latest

**Comment by GC-spigot** [comment]
They do spawn fine for me, remember that some mobs require grass / sunlight etc
