### ISSUE TITLE
[Issue] Can hit citizens

### ISSUE THREAD

**Issue by Yoloman0013** [GC-spigot/AdvancedSpawners#127]
**Describe the bug**
You can hit ncp - citizens (free version)

**To Reproduce**
A way to reproduce the video
just hit citizen 
**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version: Spigot 1.8.8
- Plugin Version 2.2.9

**Comment by Yoloman0013** [comment]
2.2.10 still same

**Comment by GC-spigot** [comment]
Found the issue! It was due to me keeping the custom names shown when the issue only happens if custom names are not shown. Will be resolved.
