### ISSUE TITLE
[Issue] Looting default enchantment does not work

### ISSUE THREAD

**Issue by MagnusMelbye** [GC-spigot/AdvancedSpawners#128]
**Describe the bug**

When a player slays a mob (dosn't matter wich type) with a looting sword, the mob drops the same amount as default with no enchants.

This has been tested with a looting 3-10-100 sword, and the drops stays the same.

**Server Information (please complete the following information):**
PaperSpigot 1.16.1
- Plugin Version 2.2.8
* Slime/magma cubes keeps duplicating into bigger mobs when killed

**Comment by GC-spigot** [comment]
Fixed
