### ISSUE TITLE
[Issue] Multiple Issues

### ISSUE THREAD

**Issue by ArchieWasTaken** [GC-spigot/AdvancedSpawners#129]
**Describe the bug**
[FIRST BUG] Mobs sometimes become almost ghost mobs not being able to be killed, they also sometimes don't despawn.

[SECOND BUG] Mob won't despawn and users are able to put items on the armor stands.

[THIRD BUG] Mob will spawn then instantly despawn.

[FOURTH BUG] Mob will sometimes not be complete (e.i. missing body parts)

**To Reproduce**
Place spawners and let it happen... I guess...

**Screenshots / Video**
https://paste.archie.digital/evosenodih.shell [ERRORS IN CONSOLE]

http://archie.digital/i/lhzbd.png [FIRST BUG SS]
http://archie.digital/i/4nvty.png [FIRST BUG SS]

http://archie.digital/i/81yxd.png [SECOND BUG SS]
http://archie.digital/i/dgu3t.png [SECOND BUG SS]

http://archie.digital/i/x3f28.png [FOURTH BUG]

**Server Information (please complete the following information):**
 - Minecraft Version: Voltane 1.8.8
- Plugin Version: 2.2.6

**Comment by GC-spigot** [comment]
Can you show your plugin list? I believe this will be an issue with another plugin

**Comment by ArchieWasTaken** [comment]
http://archie.digital/i/92z8k.png Very Sorry for the late reply.
