### ISSUE TITLE
[Issue]Superiorskyblock compatibility

### ISSUE THREAD

**Issue by magiciangoh** [GC-spigot/AdvancedSpawners#130]
**Describe the bug**
It appears that the latest advancedspawners (2.2.10) plugin doesn't support the latest superiorskyblock (version 1.1.1) spawner counting/stacking in island top because I tried it with superiorskyblock2 (version 1.0.0), and it works fine. I've contacted the developed of superiorskyblock and he told me to contact you to add the support. Thank you.

**To Reproduce**

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [2.2.10]

**Comment by GC-spigot** [comment]
That's very backwards, the person who has the Island Top has to add support, not me. AdvancedSpawners is not a 'Island Top' plugin and everything is available with the API to add support.
