### ISSUE TITLE
[Issue] Not hooking into WildStacker

### ISSUE THREAD

**Issue by AddmanMinecraft** [GC-spigot/AdvancedSpawners#131]
**Describe the bug**
AS will not hook intoWildStacker

**To Reproduce**
Load a server with both AdvancedSpawner & WildStacker

**Screenshots / Video**
N/a

**Server Information (please complete the following information):**
 - Beer Spigot [1.8.8]
- Plugin 2.2.12

**Comment by GC-spigot** [comment]
WildStacker version?

**Comment by AddmanMinecraft** [comment]
3.1.1

**Comment by AddmanMinecraft** [comment]
Update?

**Comment by AbooseYou** [comment]
I also have this happing

**Comment by GC-spigot** [comment]
Will be looking into this now

**Comment by ArefyNetwork** [comment]
Hi, how's this issue going? I keep waiting for a solution.
