### ISSUE TITLE
Mobs Can't Die by Fall Damage and Lava + Mobs Can't Spawn in Air[Issue]

### ISSUE THREAD

**Issue by NeonVisions** [GC-spigot/AdvancedSpawners#132]
**Describe the bug**
[BUG 1] Hostile mobs seem to be the only mobs that can die via lava or fall damage. Passive mobs are unable to be burnt or experience fall damage
[BUG 2] Mobs cannot spawn in-air

**To Reproduce**
[BUG 1] Attempt to burn or drop passive mobs
[BUG 2] Attempt to place a block or slab above the spawner and nothing will spawn

**Screenshots / Video**
https://gyazo.com/ecbfb7bca1fef36f69f7e48889aeea57

**Server Information (please complete the following information):**
 - Minecraft Version 1.15.2
- Plugin Version 2.2.14

Thanks

**Comment by GC-spigot** [comment]
Spawn points aren't modified at all - whatever mobs spawn in air will do after, though they won't if there's a mob near which they can stack to, will look into passive mobs not burning
