### ISSUE TITLE
Big bug with Spawnershop

### ISSUE THREAD

**Issue by Endphoenix** [GC-spigot/AdvancedSpawners#137]
If you type in /spawnershop, it opens the SpawnershopGUI. The problem is that you can easily take the Spawners out of the GUI and use them.
I deoped myself and it worked out anyway.

A short Video:

[Advancedspawners Bug.zip](https://github.com/GC-spigot/AdvancedSpawners/files/4981178/Advancedspawners.Bug.zip)

My Spawnershop Config:

[spawnerShopyml.zip](https://github.com/GC-spigot/AdvancedSpawners/files/4981186/spawnerShopyml.zip)

Minecraft Spigot 1.14.4 Version 2.3.1

**Comment by GC-spigot** [comment]
Fixed! It was due to colors in the name.

**Comment by Endphoenix** [comment]
Ok, thank you very much!

**Comment by Endphoenix** [comment]
But there is no uptade?
