### ISSUE TITLE
EntityDamageHandler & DeathDropEvent causing alot of lag[Issue]

### ISSUE THREAD

**Issue by SkyblockinDev** [GC-spigot/AdvancedSpawners#139]
**Describe the bug**
Hi, it's not really a bug but I really need some help. I have a Skyblock server and recently it has become quite laggy due to  EntityDamageHandler & DeathDropEvent from your plugin. I'm not sure how to sort this/the best way to reduce this lag please help if you have any idea. I am using Clearlag and server booster which has helped a bit but still experiencing lag spikes due to the number of spawners some island have

Timing Report: https://timings.aikar.co/?id=d9c4b6d4abea4110a1aa712e20a2255e

 - Minecraft Version: Spigot 1.8.8
- Plugin Version: 2.3.2

**Comment by GC-spigot** [comment]
Seems to be a lag issue with drops, will look into it.
