### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by xThorlak** [GC-spigot/AdvancedSpawners#14]
Okay so I have the latest version of AdvancedSpawners, I use another plugin called "JetsMinions" it uses small armor stands to make minions, whever I have AdvancedSpawners installed I cannot pickup minions by left clicking on them, it just damages the Minions (I tried deleting AdvancedSpawners, came to the conclusion AdvancedSpawners is 100% the issue)

Server version 1.8.9 PaperSpigot

**Comment by GC-spigot** [comment]
Should be fixed in next update
