### ISSUE TITLE
Config - Randomspawning dosnt work

### ISSUE THREAD

**Issue by Aliphant18** [GC-spigot/AdvancedSpawners#140]
Hello,

in the Config there is a Point called Random-Spawning. Also, with 100% Chance to spawn a Mob, nothing happend

I use the newset Version from advancedSpawners: 2.3.3

I have a Cloudnet-V3 Server with Aegis [Bungeecord, its Waterfall] and Paperspigot 1.8. Also i use Viaversion for 1.8-1.15
Also, i put the World in the config etc, but nothing will work

Pls fix this, thanks

**Comment by Endphoenix** [comment]
I have the same Problem, but on Spigot 1.14.4 and without Viaversion

**Comment by kacperleague9** [comment]
Same problem. 1.12.2 Paper.

**Comment by GC-spigot** [comment]
Fixed
