### ISSUE TITLE
[mobs are invisible]

### ISSUE THREAD

**Issue by ArneBAR** [GC-spigot/AdvancedSpawners#142]
**Describe the bug**
When the spawner spawns a mob it is invisible

**Screenshots / Video**
https://www.youtube.com/watch?v=PwDL5RX_7Dc&feature=youtu.be

**Server Information (please complete the following information):**
 - Minecraft Version [Paperspigot from 1.8.x to 1.12.2]
- Plugin Version [2.3.3]

**Comment by GC-spigot** [comment]
What plugins are you using?
