### ISSUE TITLE
Multiple problem

### ISSUE THREAD

**Issue by Unspecified13** [GC-spigot/AdvancedSpawners#15]
**Describe the bug**
first beug since the last update the commande to give spawner don't work when i do : as itemSpawner Killer_Strike Monkey 1 1 plugin say : invalid material but with the second last version command work. 

second problem we can upgrade spawner but i have set 2 spawner one level 4 et one level 1 and i have look how many mob spawn and between level 1 and level 4 no difference we have the same number off mobs who spawn 

i add one suggestion , i have try and it's work i have create a diamond spawner with the command 
as itemSpawner Killer_Strike 264 1 1 he can be incredible for you plugin to say we can do that :) only problem we can definir the spawn off the spawner so the spawner spawn to many diamond 

and also it can be nice for people who have buy a spawner to retake them with a pickaxe for that or anything else ? 

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version last one

**Comment by GC-spigot** [comment]
1st issue - you're giving item spawner with mob name, use a material name for item spawners
2nd issue - will look into this
3rd - Okay I will think about how to change it
4th - Just have silk touch on pickaxe and mine spawners
