### ISSUE TITLE
[Issue] Bypassing Bentobox settings

### ISSUE THREAD

**Issue by Kesims** [GC-spigot/AdvancedSpawners#152]
**Describe the bug**
I have SkyBlock server and I am using Bentobox. In Bentobox (Bskyblock) there is option to disable mob spawning on the island. But with your plugin it is not working, mobs are spawning like crazy.

Would it be possible to fix that? It is pretty big issue for me. Thx.

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.16.2]
- Plugin Version [latest (2.4.5)]

**Comment by GC-spigot** [comment]
Fixed
