### ISSUE TITLE
Plugin IP[Issue]

### ISSUE THREAD

**Issue by ExceptedPrism3** [GC-spigot/AdvancedSpawners#155]
**Describe the bug**
Hello i have this IP issue thing, [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs. And I'm using the plugin on my server only and it's IP is dedicated

**Screenshots / Video**
![Annotation 2020-09-06 214606](https://user-images.githubusercontent.com/68008341/92391070-eeb91100-f113-11ea-82bb-9cf5fc46af95.png)

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [8.0.0-Pre45]

**Comment by myiume** [comment]
This means your plugin exceeded the number of activations for its license, meaning that you are using a copy of the plugin that is used by multiple ips. Do you have a legit purchased copy?

https://www.spigotmc.org/resources/%E2%AD%95%EF%B8%8F-advancedenchantments-%E2%9C%85-200-custom-enchants-%E2%AD%90-create-custom-enchantments-%E2%9C%A8-1-8-1-16-30-sale.43058/

**Comment by ExceptedPrism3** [comment]
Yep, this issue it been fixed thanls
