### ISSUE TITLE
Plugin bypass WorldGuard flags

### ISSUE THREAD

**Issue by Jakogaming** [GC-spigot/AdvancedSpawners#158]
I have problem with plugin. So when i put plugin on server players can kill animals on spawn where is flag for no killing animals.
the massage pop out "You cant harm animals here" but they still receiving DMG and die after few hits. When i remove plugin everything work fine. I have type of serwer with horses on spawn and they cant be killable. WHAT CAN I DO !

**Comment by GC-spigot** [comment]
Fixed
