### ISSUE TITLE
Attack damage not working

### ISSUE THREAD

**Issue by Niko302** [GC-spigot/AdvancedSpawners#159]
**Describe the bug**
When changing damage of attack of the mob it doesn't change in .mob files

**To Reproduce**
When changing damage of attack of the mob it doesn't change the damage in game.

**Screenshots / Video**
https://i.ibb.co/rpt2X6N/health-damage.png
**Server Information (please complete the following information):**
 - Paper 259
- Plugin Version 2.8.9

**Comment by GC-spigot** [comment]
Fixed
