### ISSUE TITLE
[Issue] Fallback gui not working

### ISSUE THREAD

**Issue by mattisadev** [GC-spigot/AdvancedSpawners#165]
**Describe the bug**
When I disable the SpawnerGUI.yml, the description explains that if I have the upgrades enabled it will fallback to the upgrades gui. It does not...

**To Reproduce**
  - Set 'enabled: false' in SpawnerGUI,yml and 'enabled: true' in upgrades.yml
  - Restart server and give yourself a spawner
  - Place spawner and attempt up the upgrades menu

**Screenshots / Video**

**Server Information (please complete the following information):**
 - PaperSpigot 1.16.4
 - 2.10.1

**Comment by GC-spigot** [comment]
Fixed
