### ISSUE TITLE
[Issue] Spawners with different levels not stacking

### ISSUE THREAD

**Issue by mattisadev** [GC-spigot/AdvancedSpawners#166]
**Describe the bug**
When I have two spawners of the same type but different levels (2x Pig spawners level 1 and level 2), the spawners will not stack with each other. They will stack with other spawners with the same type and level though. 

**To Reproduce**
  - Give yourself a level 1 pig and a level 2 pig spawner
  - Place the level 1 pig spawner down and place the level 2 pig spawn near it (within the radius you set)

**Server Information (please complete the following information):**
 - PaperSpigot 1.16.4
 - 2.10.1

**Comment by frosxt** [comment]
This can't be serious. It's a different level, of course, it won't stack.

**Comment by GC-spigot** [comment]
^
