### ISSUE TITLE
[Issue] Spawners will not stack when placing on the actual spawner block

### ISSUE THREAD

**Issue by mattisadev** [GC-spigot/AdvancedSpawners#167]
**Describe the bug**
When you attempt to stack a spawner mid-air (when there are no other blocks besides the spawner) it will not stack

**To Reproduce**
  - Have a spawner floating in the air (or on the ground) and attempt to place another spawner of the same type on top of (or on the side of) it

**Server Information (please complete the following information):**
 - PaperSpigot 1.16.4
 - 2.10.1

**Comment by GC-spigot** [comment]
Shift + right-click to place them
