### ISSUE TITLE
[Issue] Hologram 'activateOnRightClick: true' not working

### ISSUE THREAD

**Issue by mattisadev** [GC-spigot/AdvancedSpawners#168]
**Describe the bug**
When I enabled 'activateOnRightClick' the holograms still show up

**To Reproduce**
set 'activateOnRightClick: true' in config.yml

**Server Information (please complete the following information):**
 - PaperSpigot 1.16.4
 - 2.10.1

**Comment by Thefluffypvper1** [comment]
I had the same issue
