### ISSUE TITLE
[Issue] /as spawnmob <any mob> gives an error

### ISSUE THREAD

**Issue by mattisadev** [GC-spigot/AdvancedSpawners#169]
**Describe the bug**
When I use /as spawnmob <any mob> it spawns an invisible silverfish and throws [this error](https://pastebin.com/r5KxntCb)

**To Reproduce**
Use the /as spawnmob command but use a cow or pig, etc 

**Server Information (please complete the following information):**
 - PaperSpigot 1.16.4
 - 2.10.1

**Comment by GC-spigot** [comment]
It's for custom mobs only
