### ISSUE TITLE
[Issue] Kills whole stack when there are 2 mobs in stack

### ISSUE THREAD

**Issue by mattisadev** [GC-spigot/AdvancedSpawners#170]
**Describe the bug**
When there are two mobs in a stack (x2 Pig) and you kill it, the whole stack (x2 pig) will die and drop the drops.

**To Reproduce**
Somehow get a stack of 2 mobs (2x Pig) and kill it, the whole stack will die

**Server Information (please complete the following information):**
 - PaperSpigot 1.16.4
 - 2.10.1

**Comment by GC-spigot** [comment]
Fixed
