### ISSUE TITLE
Excessive Mobs Spawn

### ISSUE THREAD

**Issue by coopersully** [GC-spigot/AdvancedSpawners#172]
Whenever mob stacking is turned to false, excessive mobs begin to spawn around the server. Players encounter up to 40 mobs of one type at a time, encountering 20 witches or 15 zombies instead of one. At one point, the server even spawned 1.4 billion bees from one bee. It seems to be duplicating them.

 - Minecraft Version [PaperSpigot 1.16.4]
 - Plugin Version [2.10.1]

**Comment by Cris9807** [comment]
Still not fixed with the latest version ...
Should that be premium support for a paid plugin?

**Comment by GC-spigot** [comment]
Fixed!
