### ISSUE TITLE
stack problem

### ISSUE THREAD

**Issue by Unspecified13** [GC-spigot/AdvancedSpawners#18]
**Describe the bug**
when a spawner is spawning you have like 20 pigzombie . iff you kill 1 pigzombie the pig disapear (you have normaly 20 mob not one) look the gif 
**To Reproduce**

https://gyazo.com/c58205d95f8e1db4874fe0e63904a71f

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version last version

**Comment by GC-spigot** [comment]
This can happen if:
1) These mobs were spawned before restart
2) You have a second mob stacking plugin

Make sure these aren't the case, I will look into this for next update.

**Comment by Unspecified13** [comment]
@GC-spigot my server have don't restart since 1 week and i have set the spawner and have wait the spawn so no they was not here before de restart 

i don't have a second mob stacking plugin i juste have your plugin and nothing else i already have sent you my plugin list in discord and you have check it
