### ISSUE TITLE
[Issue] Incompatible with Slimefun

### ISSUE THREAD

**Issue by Hellcode48** [GC-spigot/AdvancedSpawners#181]
**Describe the bug**
Using this plugin basically messes up slimefun's spawner system and there's no way to disable spawners in Advanced Spawners (I set config option for spawner config to false)

**To Reproduce**
Place a spawner, try to mine with Pickaxe of Containment

**Server Information (please complete the following information):**
 - Paper Spigot 1.16.4
- 2.11.0

**Comment by GC-spigot** [comment]
If you disable spawner system in AdvancedSpawners, then there won't be a point in keeping AdvancedSpawners on the server
