### ISSUE TITLE
[Issue] Villager/Armor stand

### ISSUE THREAD

**Issue by Xitryne** [GC-spigot/AdvancedSpawners#189]
It is impossible to change the villagers' job when it stacks up, so it would be nice to be able to choose that only the monsters that come out of the generator stack up and not the others.
I also have a problem with the Armor Stand since I added the plugin. Players are able to break Armor Stand on reward boxes for example. I tried to do it by removing the plugin and I couldn't break the Armor Stand anymore. The problem occurs with the RevoltCrates and JetsSellChests plugins.

**Server Information (please complete the following information):**
 - Minecraft Version [Spigot 1.15.2]
- Plugin Version [2.11.10]

**Comment by GC-spigot** [comment]
You can add villagers to stacking blacklist, setting is called `stackingBlacklist`
For armor stands, that should be now fixed
