### ISSUE TITLE
[Issue] Stacking World Blacklist not working

### ISSUE THREAD

**Issue by frosxt** [GC-spigot/AdvancedSpawners#198]
**Describe the bug**
Adding worlds to the world blacklist option doesn't change anything, reloading the plugin via /as reload or reloading it via plugman, and restarting also does not solve the issue. Disabling stacking globally works completely fine.

**To Reproduce**
1. Add a world to the stacker blacklist setting
2. Reload, then test.

**Screenshots / Video**
Not needed.

**Server Information (please complete the following information):**
- TacoSpigot 1.8.8
- Plugin Version 2.11.2

**Comment by GC-spigot** [comment]
Fixed
