### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Sneakynija700** [GC-spigot/AdvancedSpawners#202]
**Describe the bug**
I have changespawnerwithmonsteregg:true
And it does change the mob but I doesn’t update the holo sign and it spawns the new mob with the old one.
**To Reproduce**
Change spawner with mob egg

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.16.5
- Plugin Version 2.11.2

**Comment by GC-spigot** [comment]
Fixed
