### ISSUE TITLE
[Issue] It gives an error message when a 16-32-64 spawner is placed in batch.

### ISSUE THREAD

**Issue by LavivaNW** [GC-spigot/AdvancedSpawners#206]
**Describe the bug**
It gives an error message when a 16-32-64 spawner is placed in batch.

**Screenshots / Video**
https://s4.gifyu.com/images/ErrorMessage.gif

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 3.0.6]

**Comment by GC-spigot** [comment]
@LavivaNW Please provide the error from console, I am not having this issue
