### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Krejzu** [GC-spigot/AdvancedSpawners#207]
Describe the bug
- Comments are still being deleted in config.yml
- Ingering in vanilla mobs spawning (spawn 3 or 4 out of 1 mob) - spawningAmount: '1-3' isnt working
- % chance for spawner dropping with silktouch isnt working at all - setting for 100% (perm without numbers at end) or nothing
- Drop exp and normal loot is disabled from spawners that are spawned naturally

(These bugs were reported long time ago by other users, and still thats happening.

To Reproduce
A way to reproduce the video

Screenshots / Video

Server Information;
 - Minecraft Version PaperSpigot 1.16.5
- Plugin Version 3.0.4

**Comment by GC-spigot** [comment]
1 - This is a global issue for all plugins with the utility Spigot/Bukkit users for YML files, been this way for at least 8 years.
2 - Will be fixed
3 - Fixed
4 - Cannot recreate
