### ISSUE TITLE
Language File not affecting plugin at all. [Issue]

### ISSUE THREAD

**Issue by ZNChano** [GC-spigot/AdvancedSpawners#208]
**Describe the bug**
Within the language file, in my case, English, there is an option to edit the way the Spawner Item is Titled and Lored. Yet, when I give myself a spawner, a blaze for example, it appears as "Blaze Spawner" with the yellow name and gray "Spawner". There is no lore and even if I attempt to change the title in the language file, that doesn't do anything either,

**To Reproduce**
Install the plugin, give yourself a spawner, and look at the spawner

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/67173433/114795568-d9b4f800-9d5c-11eb-9efa-db88794a44a1.png)

![image](https://user-images.githubusercontent.com/67173433/114795579-e20d3300-9d5c-11eb-8168-a634fcbc1c7d.png)

**Server Information (please complete the following information):**
 - Minecraft Version: PaperSpigot 1.16.5
- Plugin Version: 3.0.9

**Comment by ZNChano** [comment]
Also I realize in the first screenshot it says "Dropped Item Spawner".... That is my bad, I accidentally screenshotted an iron ingot spawner instead of the blaze. But the blaze looks exactly like that, just with "Blaze" instead of dropped item

**Comment by GC-spigot** [comment]
Fixed!
