### ISSUE TITLE
[Issue] KILL_MOB effect with AdvancedEnchantments causes glitched invulnerable mobs with AdvancedSpawners Stackable Mobs

### ISSUE THREAD

**Issue by BugReporter124** [GC-spigot/AdvancedSpawners#225]
Whenever you kill a stacked mob from AdvancedSpawners, with an enchantment from AdvancedEnchantments that has the KILL_MOB effect, it glitches the mob to a point where it is invulnerable.

https://user-images.githubusercontent.com/39203381/118384057-d1084980-b5c8-11eb-84fc-459eb02747d7.mp4

 - Minecraft Version 1.16.5
- Plugin Versions: AdvancedEnchantments 8.0.6, AdvancedSpawners 3.1.7

**Comment by GC-spigot** [comment]
Looking into this!
