### ISSUE TITLE
[Issue] Spawners

### ISSUE THREAD

**Issue by Pikaronga** [GC-spigot/AdvancedSpawners#226]
**Describe the bug**
When a block is placed above a spawner it gets disconnected from reality and when it's broken drops nothing. 

**Server Information (please complete the following information):**
 - Minecraft Version PurPur 1.16.5
- Plugin Version 3.1.7

**Comment by GC-spigot** [comment]
It's a visual minecraft glitch, the block doesn't actually get placed. I'll see what can be done.
