### ISSUE TITLE
[Issue] Plugin not loading at all on a fresh Purpur 1.16.5 installation

### ISSUE THREAD

**Issue by MilleniumModsSources** [GC-spigot/AdvancedSpawners#230]
**Describe the bug**
The plugin (v3.2.0) with a full default configuration does not load at all when starting a Purpur 1.16.5 server, this is the entire log:
https://pastebin.com/g2NZN46S

**To Reproduce**
Just try to load the plugin on a completely fresh installation of Purpur 1.16.5 (Haven't tried to use it on Paper or Spigot).

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
- Server version: Purpur 1.16.5 build 1118.
- Plugin version: 3.2.0
- Java version: Latest Java 8.
- Other plugins? No, this is the only one.
- Tried to fully reset the world, didn't work.

**Comment by GC-spigot** [comment]
Update, a small update was posted to fix it

**Comment by MilleniumModsSources** [comment]
Seems that the update isn't published at the plugin site, just on Spigot
