### ISSUE TITLE
[Issue] Plugin is disabling itself

### ISSUE THREAD

**Issue by carlitoskraft** [GC-spigot/AdvancedSpawners#233]
**Describe the bug**
When i try to use any command from this plugin, an internal error message appears. Apparently the plugin is disabling itself.

**To Reproduce**
I download the last version of AdvancedSpawners for spigot 1.16.5.
My server is Paper 1.16.5 #706
My other plugins: 
actionhealth, blocklocker, bstats, floodgate, geyser, sleep, skinsrestorer, protocollib

**Screenshots / Video**
![last error](https://user-images.githubusercontent.com/84526608/119015522-5ac06a00-b96f-11eb-8c6f-68f3daa50116.jpg)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. Paper 1.16.5 #706]
- Plugin Version [e.g. 3.2.0]

**Comment by GC-spigot** [comment]
Fixed
