### ISSUE TITLE
People don't die

### ISSUE THREAD

**Issue by EternalBlizzardd** [GC-spigot/AdvancedSpawners#239]
People don't seem to die, when they fall in lava or in the void or whatever and they get to half a heart health, it heals them to full and it creates a loop... They can't die

![IMG_20210523_232259](https://user-images.githubusercontent.com/84684397/119275487-16a6c100-bc1e-11eb-9432-b72df14fa27e.jpg)

 - Minecraft Version 1.16.5
- Plugin Version 3.2.3

**Comment by jarek11223349** [comment]
I have the same problem

**Comment by ghost** [comment]
Reported in ticket on several occasions, vouched by Cobs.

**Comment by GC-spigot** [comment]
Fixed
