### ISSUE TITLE
The inventory disappears after /as editor

### ISSUE THREAD

**Issue by vdl19** [GC-spigot/AdvancedSpawners#241]
**Describe the bug**
Hello, I just installed the latest version 3.2.3
So after using /as editor indeed it seems that mobs are not invincible anymore but there is a bug.
Once done /as editor, choose a mobs then quit even if we change nothing we lose absolutely all our inventory.

**To Reproduce**
Once done /as editor, choose a mobs then quit even if we change nothing we lose absolutely all our inventory.

**Screenshots / Video**
Before /as editor :
![image](https://user-images.githubusercontent.com/80985545/119326190-eee94480-bc81-11eb-986e-aafa3ba6d6ec.png)

After /as editor and having clicked on a mobs to modify and without modifying it just by going out it is enough
![image](https://user-images.githubusercontent.com/80985545/119326222-f6a8e900-bc81-11eb-8fef-e76af0fe924d.png)

**Server Information (please complete the following information):**
Serveur Paper 1.16.5 #724
Java 11
AdvancedSpawner 3.2.3

**Comment by CobsMC** [comment]
Reported in ticket, could reproduce, vouched by Cobs.

**Comment by vdl19** [comment]
Hello, still the same problem with version 3.2.4, I just installed it this morning. Loss of complete inventory when you go to edit a mob and you come out.

**Comment by vdl19** [comment]
Hello, still the same problem with version 3.2.5

**Comment by GC-spigot** [comment]
It’s an extremely minor issue, you do not need to bump it. This command is only for admins and we expect them not to have any items in inventory.
