### ISSUE TITLE
AdvancedSpawners - textures do not appear.  

### ISSUE THREAD

**Issue by Revens-Craft** [GC-spigot/AdvancedSpawners#242]
**Describe the bug**
When I click on textures to create or edit a mob, there is simply no texture, I am using the latest version {3.2.4}. I tried to remove the plugin and the plugin folder from my server but nothing worked, I will leave some prints below.

**Screenshots / Video**
![aspawners](https://user-images.githubusercontent.com/84817131/119583450-0b2dd400-bd9d-11eb-9432-2d78120bf744.gif)

**Server Information (please complete the following information):**
 - Minecraft Version [Spigot 1.13.2]
- Plugin Version [3.2.3] and [3.2.4] tested on both versions of the plugin.

**Comment by MilleniumModsSources** [comment]
This has been an issue for quite a long time, but for now, I just recommend using base64 skins, you can get the base64 value from this page: https://minecraft-heads.com/ , simply choose whatever head that you want, scroll down on its page and copy the "Other - Value" text.

![image](https://user-images.githubusercontent.com/76138687/119837646-cb680900-bed0-11eb-9915-5388d4c9df17.png)
