### ISSUE TITLE
[Issue] Bear.amob file missing

### ISSUE THREAD

**Issue by Nutmegan** [GC-spigot/AdvancedSpawners#250]
**Describe the bug**
The config file for the the Bear.amob is missing from the 3.2.4 jar.

**To Reproduce**
Do a clean install of AdvancedSpawners  version 3.2.4 on a paper server. Run the jar. Stop the server. Open the AdvancedSpawners plugin folder on the server. Open the Custom Mobs folder. There is no Bear.amob file.

**Screenshots / Video**
<img width="495" alt="Screen Shot 2021-06-03 at 9 47 12 AM" src="https://user-images.githubusercontent.com/9382508/120677976-e00a4b00-c454-11eb-988c-0d8fedaa4d4d.png">
<img width="713" alt="Screen Shot 2021-06-03 at 9 51 22 AM" src="https://user-images.githubusercontent.com/9382508/120678008-e698c280-c454-11eb-8914-ba177ab8cd39.png">

**Server Information (please complete the following information):**
 - Minecraft Version paper 16.4 #384 (sorry, just realized my local test version is pretty out of date.)
- Plugin Version 3.2.4

**Comment by GC-spigot** [comment]
Fixed
