### ISSUE TITLE
Lag Spike

### ISSUE THREAD

**Issue by KickSquareMC** [GC-spigot/AdvancedSpawners#253]
I just ran into a bit of a lag spike, according to a timings report advancedspawners is causing it. Is this a known bug? TPS dropped from 20.0 to ~16 for 30-60 seconds, seems fine now. Wasn't doing anything with the plugin while it happened, although I was in spawning-range of a Tiger spawner so it was probably spawning every now and then

![image](https://user-images.githubusercontent.com/75801179/121754731-2e10f580-caca-11eb-9fc9-937902f099e8.png)

**Comment by GC-spigot** [comment]
It happened once, you'd need to post full timings link for me to tell what is going on.
