### ISSUE TITLE
[Issue] BUG with /tokens balance (nick)

### ISSUE THREAD

**Issue by MrDeathMatch** [GC-spigot/AdvancedSpawners#256]
**Describe the bug**
I will be brief, the bug is that when I place / tokens balance (nick) I get the same amount of tokens that I have when I should get the player's

**To Reproduce**
-
**Screenshots / Video**
![image](https://user-images.githubusercontent.com/85938873/122047111-5c7e2180-cda5-11eb-8cff-3530f2403bcf.png)

**Server Information (please complete the following information):**
 - PaperSpigot 1.8.8
- 2.11.0

**Comment by GC-spigot** [comment]
Wrong github
