### ISSUE TITLE
[Issue] Mob spawning error

### ISSUE THREAD

**Issue by mrxbox98** [GC-spigot/AdvancedSpawners#259]
**Describe the bug**
When you try to spawn the dragon mob it throws an error and doesn't work

**To Reproduce**
Start server
Do /as spawnMob dragon

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29240392/122847949-75169c00-d2bd-11eb-9cb5-4c4c915fed71.png)
![image](https://user-images.githubusercontent.com/29240392/122848055-a98a5800-d2bd-11eb-9539-27091c26ed38.png)

**Server Information (please complete the following information):**
PaperSpigot 1.8.8
Advanced Spawners 3.2.7

**Comment by mrxbox98** [comment]
In the second screenshot, it says beerSpigot but I also tried it with paperSpigot and got the same exact error.

**Comment by GC-spigot** [comment]
Fixed next update
