### ISSUE TITLE
[Issue] Failed to load drop for Bear

### ISSUE THREAD

**Issue by mrxbox98** [GC-spigot/AdvancedSpawners#260]
**Describe the bug**
Error during startup that says it can't load the mob drop for a Bear

**To Reproduce**
Start your server

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29240392/123014421-17e12000-d37b-11eb-9c20-489493d974d8.png)
![image](https://user-images.githubusercontent.com/29240392/123014432-1dd70100-d37b-11eb-99ff-fb774dd856de.png)

**Server Information (please complete the following information):**
 - BeerSpigot 1.8.8 fork of TacoSpigot 1.8.8
- AdvancedSpawners 3.2.8

**Comment by GC-spigot** [comment]
Fixed
