### ISSUE TITLE
[Issue] Game Breaking Anvil Issue

### ISSUE THREAD

**Issue by qSeek** [GC-spigot/AdvancedSpawners#261]
**Describe the bug**
Basically you can't apply more than 1 vanilla enchantments on items after the AE 8.3.4 update.

**To Reproduce**
Get an item with any vanilla enchantment and try to apply one more enchantment using books in anvil.

**Screenshots / Video**
https://i.gyazo.com/ee9037ab1ff2eee39e3154521986b996.gif

**Server Information (please complete the following information):**
 - Paper 1.17
- Plugin Version 8.3.4

**Comment by GC-spigot** [comment]
Wrong github
