### ISSUE TITLE
[Issue] All spawners turn into SilverSpawners 

### ISSUE THREAD

**Issue by itsIrish** [GC-spigot/AdvancedSpawners#264]
I am having issues with Advanced Spawners The spawners place. But the custom mobs are just invisible silverfish. Even the display doesn't work Yes, all normal Minecarft Mobs like cows and pigs work. Just not the custom mobs. 

Also, support on the discord are absolutly disgusting. I am a paying customer I deserve respect.

**Comment by GC-spigot** [comment]
Hi! My apologies about the support, we're trying our best but there is a lot of tickets opened daily. 

Can you provide your `latest.log` file from logs folder and latest file from `AdvancedSpawners/pluginLogs` folder? Thanks

**Comment by itsIrish** [comment]
So they work again, however sometimes they turn into silverfish now and then

**Comment by GC-spigot** [comment]
Can you zip all of your files from `AdvancedSpawners/pluginLogs` folder and send them? With this I could possibly find the underlying issue.

**Comment by itsIrish** [comment]
[AdvancedSpawnerspluginLogs.zip](https://github.com/GC-spigot/AdvancedSpawners/files/6765155/AdvancedSpawnerspluginLogs.zip)
Here you go :)
