### ISSUE TITLE
[Issue] Bear Mob Drop

### ISSUE THREAD

**Issue by mrxbox98** [GC-spigot/AdvancedSpawners#265]
**Describe the bug**
During the plugin loading, an error is thrown

**To Reproduce**
Install the plugin and start your server

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/29240392/124210111-bc601200-da9f-11eb-82a2-b91959f496d7.png)
![image](https://user-images.githubusercontent.com/29240392/124210130-c3872000-da9f-11eb-8b88-afb2f77a5d5a.png)
These are the same error message I just couldn't fit it into one screenshot

**Server Information (please complete the following information):**
 - BeerSpigot 1.8.8 (TacoSpigot fork)

**Comment by GC-spigot** [comment]
Duplicate of #260
