### ISSUE TITLE
AS Issue List

### ISSUE THREAD

**Issue by Oliver-Joe-Simmons** [GC-spigot/AdvancedSpawners#267]
AS:
- Custom mob spawning breaks after server restart, custom mobs don't spawn
- Even though stacking is set to false in configs, mobs still stack
- Custom mob rendering seem to be really broken as mobs appear spread apart and disfigured
- Mobs added to spawner shop are not been displayed
- Horses/Mobs like horses re spawn when killed, believe this is because of grief prevention conflicting with your plugin but can test later on as we are moving to Lands and getting rid of 
- Mobs are freezing constantly
- Big Xp Bug:  https://youtu.be/H6oJ1cZXylY
- When Stacking is enabled everything breaks

**Comment by GC-spigot** [comment]
Can you attach your `latest.log` file from `logs` folder and as well the latest file from `AdvancedSpawners/pluginLogs` folder? Would be great to see what the plugin is showing, since I can't recreate most of these issues so far.

**Comment by Oliver-Joe-Simmons** [comment]
[latest.log](https://github.com/GC-spigot/AdvancedSpawners/files/6765595/latest.log)

**Comment by Oliver-Joe-Simmons** [comment]
[07-05-2021 03-02-27.log](https://github.com/GC-spigot/AdvancedSpawners/files/6765598/07-05-2021.03-02-27.log)

**Comment by Oliver-Joe-Simmons** [comment]
Up to date logs:
[latest.log](https://github.com/GC-spigot/AdvancedSpawners/files/6832685/latest.log)
[07-16-2021 18-48-54.log](https://github.com/GC-spigot/AdvancedSpawners/files/6832688/07-16-2021.18-48-54.log)
