### ISSUE TITLE
Eggs Always Spawning Pigs [Issue]

### ISSUE THREAD

**Issue by Aquamonk** [GC-spigot/AdvancedSpawners#268]
**Describe the bug**
Hi, great plugin, I give myself different mob eggs (with /as mobEgg <player> <mob> <quantity>), but always appear pigs from these eggs. It says its a cow egg on inventory, but pigs are what spawns.

**To Reproduce**
/as mobEgg <player> <mob> <quantity>, and check out what spawns from that egg

**Screenshots / Video**
![1](https://user-images.githubusercontent.com/35933684/125211975-7c243f00-e2aa-11eb-8e77-3a9588b09723.png)

![2](https://user-images.githubusercontent.com/35933684/125211980-80505c80-e2aa-11eb-80f8-bbb0f4bf7737.png)

![3](https://user-images.githubusercontent.com/35933684/125211981-834b4d00-e2aa-11eb-90ef-5039d079e0db.png)

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.16.5
- Plugin Version Last (3.3.1)

**Comment by GC-spigot** [comment]
They were meant for custom mobs only, new update adds vanilla mob support as well!
