### ISSUE TITLE
Plugin disabled on restart

### ISSUE THREAD

**Issue by Green-newfie** [GC-spigot/AdvancedSpawners#27]
The plugin gets disabled on restart of the server.
I have the latest ProtocolLib
The server uses [tuinity](https://github.com/Spottedleaf/Tuinity) a paper fork, however even when just using paper it still didn't work.
server 1.15.2

> `[16:27:47] [Server thread/INFO]: [AdvancedSpawners] Enabling AdvancedSpawners v1.2.6
> [16:27:47] [Server thread/INFO]: [AdvancedSpawners] Loaded 7 mob configurations.
> [16:27:47] [Server thread/INFO]: [AdvancedSpawners] Loaded 2 mob animations.
> [16:27:47] [Server thread/ERROR]: Error occurred while enabling AdvancedSpawners v1.2.6 (Is it up to date?)
> java.lang.NullPointerException: null
> 	at org.bukkit.Location.getBlock(Location.java:133) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at gcspawners.SpawnersHandler.a(SpawnersHandler.java:115) ~[?:?]
> 	at gcspawners.SpawnersHandler.<init>(SpawnersHandler.java:33) ~[?:?]
> 	at gcspawners.Core.loadBasics(Core.java:146) ~[?:?]
> 	at gcspawners.Core.onEnable(Core.java:80) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]
> [16:27:47] [Server thread/INFO]: [AdvancedSpawners] Disabling AdvancedSpawners v1.2.6
> [16:27:47] [Server thread/ERROR]: Error occurred while disabling AdvancedSpawners v1.2.6 (Is it up to date?)
> java.lang.NullPointerException: null
> 	at gcspawners.Core.onDisable(Core.java:251) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:372) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:341) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Tuinity-"4b377ad"]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by GC-spigot** [comment]
Should be patched in next update
