### ISSUE TITLE
[Issue] Textures not loading on offline servers

### ISSUE THREAD

**Issue by Stibiumcraft** [GC-spigot/AdvancedSpawners#270]
Hi, I don't think it would be a bug, but if I try to edit custom mobs in the game, armourstand doesn't show up and there are a lot of such errors in the console - https://pastebin.com/Zbz0UgW7

It's similar when choosing a skin. When I use "Browsing textures" the heads have Steve head textures and when I open any category, the console is full of this https://pastebin.com/PgYGzTgW

Then I can't use the editor menu, error [10:14:06 ERROR]: Could not pass event InventoryClickEvent to AdvancedSpawners v3.3.2

Please advise me what to do to make it work. Thank you

**Server Information:**
 - Minecraft Version [PaperSpigot 1.16.5]
- Plugin Version [3.3.2] Configuration is default

**Comment by GC-spigot** [comment]
Try with latest, reopen if it happens again. Is your server in offline mode?

**Comment by Stibiumcraft** [comment]
It's still happening. Yes, my server is offline, but there is no warning about it...

**Comment by GC-spigot** [comment]
I'll look into what I can do here but since server is offline, it doesn't communicate the same way it normally would. We're not using anything special, just what spigot offers skins wise. Will check what else can be done.
