### ISSUE TITLE
DUPE BUG: Duplicated armor drops

### ISSUE THREAD

**Issue by KickSquareMC** [GC-spigot/AdvancedSpawners#273]
Stacked mobs sometimes "reincarnate" (after killing a stack) with full armor and drop x(however many mobs were in the stack) amounts of armor. For example, for a x5 skeleton the "reincarnated" mob drops x5 chestplates, etc.

This means if there's 1000x zombies in a stack with leather armor it'll drop 1000 leather armor pieces.

All I'm asking for is a simple config option

"disable-mobs-dropping-armor: true"

That would be a temporary fix, please add this ASAP.

**Comment by GC-spigot** [comment]
Fixed
