### ISSUE TITLE
[Issue] Errors and spawners changes to default after restart

### ISSUE THREAD

**Issue by Yoloman0013** [GC-spigot/AdvancedSpawners#274]
**Describe the bug**
and error https://pastebin.com/mrcmYJPi
and first error https://pastebin.com/VAydXjEf

**To Reproduce**
Restart server

**Server Information (please complete the following information):**
 - 1.8.8
- Plugin Version 3.3.2

**Comment by GC-spigot** [comment]
Can you send your logs files from the day spawners got removed? They are located in `plugins/AdvancedSpawners/pluginlogs` folder. This way I can figure out what caused it better.

**Comment by Yoloman0013** [comment]
> Can you send your logs files from the day spawners got removed? They are located in `plugins/AdvancedSpawners/pluginlogs` folder. This way I can figure out what caused it better.

[SpawnersHandler 06-09-2021 22-45-55] Loaded 0 spawners, failed to load: 0
[SpawnersHandler 06-09-2021 22-46-53] Saved 0 spawners
[SpawnersHandler 06-09-2021 22-51-56] Saved 0 spawners
[SpawnersHandler 06-09-2021 22-56-59] Saved 0 spawners
[SpawnersHandler 06-09-2021 23-02-02] Saved 0 spawners
[SpawnersHandler 06-09-2021 23-07-05] Saved 0 spawners
[SpawnersHandler 06-09-2021 23-10-21] Saved 0 spawners

**Comment by GC-spigot** [comment]
Fixed
