### ISSUE TITLE
[Can't edit Custom Mobs In game ]

### ISSUE THREAD

**Issue by Swiftly123** [GC-spigot/AdvancedSpawners#275]
**Describe the bug**
When i click to edit the settings on the custom mob In game it does nothing. I can click and click for hours, nothing happened...edit dammage or health...just impossible...And i can't create or edit anything

**Server Information (please complete the following information):**
 - Minecraft Version 1.16.4 on Spigot
 - Last Version 3.3.2

Thanks for your hlep...

**Comment by GC-spigot** [comment]
Look in console, find errors and send them here.

**Comment by Swiftly123** [comment]
It says absolutly nothing in the console

**Comment by GC-spigot** [comment]
Try opening editor, clicking around until something doesnt work then upload your `latest.log` file here or copy paste to pastebin.com

**Comment by Swiftly123** [comment]
So I downloaded the latest version and its show something in the console :

[Server thread/ERROR]: Could not load 'plugins/AdvancedSpawners-3.3.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `gc.spawners.Core'
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[spigot-1.16.4.jar:git-Spigot-a93cbb1-7a6c3c9]
