### ISSUE TITLE
[Issue] Spawner data loss. 

### ISSUE THREAD

**Issue by Pikaronga** [GC-spigot/AdvancedSpawners#277]
**Describe the bug**
There is still a severe issue with data saving as spawners are still randomly dissapearing. 

**Server Information (please complete the following information):**
 - Minecraft Version Purpur 1.16.5
- Plugin Version 3.3.2

**Comment by GC-spigot** [comment]
Can you send your logs files from the day spawners got removed? They are located in plugins/AdvancedSpawners/pluginlogs folder. This way I can figure out what caused it better.

**Comment by Pikaronga** [comment]
https://pastebin.com/zcCqmCKg

**Comment by Yoloman0013** [comment]
same thing on 1.8

**Comment by GC-spigot** [comment]
Fixed
