### ISSUE TITLE
 XP : bug on the XP given by the mobs of Minecraft which is not good the good account

### ISSUE THREAD

**Issue by vdl19** [GC-spigot/AdvancedSpawners#283]
**Describe the bug**
Hello, one of my players has just reported a problem with the Piglins and Zombified Piglins, it is possible that other mobs pose problems. The problem is that they only give 1 to 3 XP instead of 5 XP (or a little more depending on the equipment) so I think that they are not the only ones to cause problems. I deleted all the plugins from my server and I have 5 XP and as soon as I put AdvancedSpawners-3.3.2 back on I only have 1 to 3 XP I didn't have time to check all the other mobs in Minecraft and this player just farms the Piglins I just tested the Zombified Piglins too.
I checked the problem on my 2 servers the official one in 1.16.5 and the test one in 1.17.1 .
I confirm that it may be all mobs involved, I tested with zombies, Piglin Barbarian, spider, Blaze etc. 

**To Reproduce**
just install the plugin and check the Xp that the mobs give, for example a zombie gives 5 XP but if AdvancedSpawner is on the server it's 1 to 3 XP it's not even a fixed value and anyway well in desosu so the players who know about it are not happy with the problem...

**Server Information (please complete the following information):**
- Minecraft PaperSpigot 1.16.5 #786 + java 16  et 1.17.1 #196  + java 16
- Plugin Version 3.3.3

**Comment by GC-spigot** [comment]
Fixed
