### ISSUE TITLE
[Issue] Random 3x errors 

### ISSUE THREAD

**Issue by Yoloman0013** [GC-spigot/AdvancedSpawners#288]
**Describe the bug**
Errors
1x of errors is because phantom sound cant be executed in 1.8 other 2x idk why

**To Reproduce**
Be around custom mobs

PaperSpigot fork 1.8.8
- AdvancedSpawners v3.3.4
errors
1. https://pastebin.com/NWhnWc2d
2. https://pastebin.com/wtt4Rvxa
3. sound thing https://pastebin.com

**Comment by GC-spigot** [comment]
Fixed
