### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by kap1mc** [GC-spigot/AdvancedSpawners#29]
**Describe the bug**
If you edit the custom mobs config and restart the server it breaks, the spawner doesn't work and any mobs will just freeze there and not be hittable or anything.

**To Reproduce**
Not sure.

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/63063114/78271558-348a0180-7504-11ea-874b-626ff3bfe812.png)

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.8.8
- Plugin Version 1.2.7

**Comment by GC-spigot** [comment]
I can't do much about this, sadly server crashes can happen and they may lead to this.
