### ISSUE TITLE
PAGE

### ISSUE THREAD

**Issue by SoildOfficial** [GC-spigot/AdvancedSpawners#291]
Sorry I have another problem regarding this plugin inside gui next page and the previous page do not work, the console throws out an error that I will leave inside the pastebin so that you can see what kind of problem it is so I would ask you for help. I will leave some information about which version of the server and plugin.
Error:https://pastebin.com/gX3HbWKn
Server Version:git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Plugin Version:AdvancedSpawners-3.3.2.jar

**Comment by GC-spigot** [comment]
Hi! Try new update and let me know the issues then. We'll be able to figure this one out then.
