### ISSUE TITLE
advanced spawners is not working

### ISSUE THREAD

**Issue by IrinDeix** [GC-spigot/AdvancedSpawners#292]
I will be leaving the lasted log, the plugin does not turn on, at the very beginning there is the error

**Server Information : **
 - Minecraft Version : NachoSpigot 1.8.8
- Plugin Version : 3.3.4
[latest (17).log](https://github.com/GC-spigot/AdvancedSpawners/files/7133290/latest.17.log)

**Comment by GC-spigot** [comment]
Fixed
