### ISSUE TITLE
Mobs became invisible randomly

### ISSUE THREAD

**Issue by MilleniumModsSources** [GC-spigot/AdvancedSpawners#294]
**Describe the bug**
That's pretty much it. All custom mobs became invisible from one moment to another. I'm using Paper 1.12.2, I'm also getting no errors on the console.

**To Reproduce**
This started happening from one day to another, all custom mobs suddenly became invisible no matter what.

**Screenshots / Video**
Uploading AS3.mp4…

**Server Information (please complete the following information):**
 - Minecraft Version [Paper 1.12.2]
- Plugin Version [3.4.4-2]

**Comment by MilleniumModsSources** [comment]
https://user-images.githubusercontent.com/76138687/133872463-65bdb115-dd60-46c5-944d-0c3aeb18a0aa.mp4

**Comment by MilleniumModsSources** [comment]
Checking with the last version (3.4.0) I've noticed that when I leave the area that those mobs are in but come back (Move around 6-7 chunks away so I can't see them but they don't despawn), they actually become visible

**Comment by GC-spigot** [comment]
Likely to be a plugin conflict or some settings in server files. Have you added new plugins recently or modified anything in Spigot/Paper.yml files?
They shouldn't despawn unless aggressively removed by server

**Comment by MilleniumModsSources** [comment]
Okay so, I managed to fix it by enabling the "armor-stands-tick" at the paper.yml, sorry for taking your time with this, I'm just stupid and don't even remember why I disabled that.

Anyway, for future reference, if anyone else is having the same issue, ig this experience will help :)
