### ISSUE TITLE
[issue] menu pages and settings

### ISSUE THREAD

**Issue by D4rkBytePT** [GC-spigot/AdvancedSpawners#296]
**The bug**
The menu don't change or make anything when i try to edit the settings of the mob or change the page from the editor

**PasteBin error console**
https://pastebin.com/C4AAa0nP

**Server Information**
 - Minecraft Version [Spigot 1.8.8-R0.1-SNAPSHOT]
 - Plugin Version [v3.3.4]

**Comment by GC-spigot** [comment]
Try updating
