### ISSUE TITLE
SQLite exception on initialize - Fail on first run/no current AS files

### ISSUE THREAD

**Issue by James-Cotterill** [GC-spigot/AdvancedSpawners#297]
**Describe the bug**
SQLite exception on initialize occurs when the server is run with no current AS files

**To Reproduce**
Run latest version with no current AS files present 

**Screenshots / Video**
https://pastebin.com/JgAjcCXK

**Server Information (please complete the following information):**
 - Minecraft Version paper-1.17.1-259
- Plugin Version 3.4.0

**Comment by GC-spigot** [comment]
Fixed
