### ISSUE TITLE
[Issue]Broken mobs, blocks Falling apart

### ISSUE THREAD

**Issue by SteelsSystem** [GC-spigot/AdvancedSpawners#299]
**Describe the bug**
My first gorilla got spawned completely messed up. i did nothing but command to spawn the mob.
**To Reproduce**
Spawn a mob on my server

A way to reproduce the video

**Screenshots / Video**
https://www.youtube.com/watch?v=R4UArRB1nd8
**Server Information (please complete the following information):**
 - Minecraft Version 1.17.1
- Purpur 1.17.1 (Optimized)
This server is running Purpur version git-Purpur-1395 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: fd158ac on ver/1.17.1)

edit: I also found a floating gorilla head next to place where we were creating a test mob
![2021-10-09_14 34 42](https://user-images.githubusercontent.com/92061582/136658127-8f1cd5d8-9ddf-4e97-9108-3418c08f8e64.png)
b.

**Comment by GC-spigot** [comment]
Was it only just one mob? Are other mobs okay?

**Comment by GC-spigot** [comment]
Found the issue, working on it.
