### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by kap1mc** [GC-spigot/AdvancedSpawners#30]
**Describe the bug**
Can not place down item spawner (/as itemSpawner kap1 diamond 1 1), full console log https://mcpaste.io/9a35367644ed28b1

**Screenshots / Video**
02.04 18:54:46 [Server] ERROR Could not pass event BlockPlaceEvent to AdvancedSpawners v1.2.7
02.04 18:54:46 [Server] INFO org.bukkit.event.EventException
02.04 18:54:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:127) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:158) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
02.04 18:54:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
02.04 18:54:46 [Server] INFO Caused by: java.lang.NullPointerException
02.04 18:54:46 [Server] INFO at gcspawners.SpawnerData.i(SpawnerData.java:159) ~[?:?]
02.04 18:54:46 [Server] INFO at gcspawners.SpawnerData.a(SpawnerData.java:115) ~[?:?]
02.04 18:54:46 [Server] INFO at gcspawners.SpawnerData.<init>(SpawnerData.java:43) ~[?:?]
02.04 18:54:46 [Server] INFO at gcspawners.SpawnersHandler.a(SpawnersHandler.java:54) ~[?:?]
02.04 18:54:46 [Server] INFO at gcspawners.SpawnerPlaceEvent.a(SpawnerPlaceEvent.java:149) ~[?:?]
02.04 18:54:46 [Server] INFO at gcspawners.SpawnerPlaceEvent.a(SpawnerPlaceEvent.java:140) ~[?:?]
02.04 18:54:46 [Server] INFO at gcspawners.SpawnerPlaceEvent.a(SpawnerPlaceEvent.java:58) ~[?:?]
02.04 18:54:46 [Server] INFO at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source) ~[?:?]
02.04 18:54:46 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
02.04 18:54:46 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
02.04 18:54:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-d3e0b6f]
02.04 18:54:46 [Server] INFO ... 18 more

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.8.8
- Plugin Version 1.2.7

**Comment by GC-spigot** [comment]
Fixed
