### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by ImYenil** [GC-spigot/AdvancedSpawners#302]
**Describe the bug**
x

**To Reproduce**
https://pastebin.com/TcZsWv41

**Screenshots / Video**
X
**Server Information (please complete the following information):**
 - Minecraft Version Spigot 1.17.1
- Plugin Version 3.4.3

**Comment by GC-spigot** [comment]
What mob are you killing?

**Comment by ImYenil** [comment]
Anything

2021년 10월 19일 (화) 오후 10:20, GC-spigot ***@***.***>님이 작성:
