### ISSUE TITLE
Translations not working ( was told to open issue here)

### ISSUE THREAD

**Issue by el211** [GC-spigot/AdvancedSpawners#311]
**Describe the bug**
I translated all the enchantments yml to french but its not working well, i am not getting anything in frnench its stays in english i opened a ticket on discord on staff replicated the issue he used my yml translated file , he also noticed that if we have 10 enchantments it will work but more it wont , so he told me to open the issue here

**Comment by GC-spigot** [comment]
Wrong plugin github, this is for AdvancedSpawners
