### ISSUE TITLE
spamming console errors {IMPORTANT}

### ISSUE THREAD

**Issue by el211** [GC-spigot/AdvancedSpawners#313]
[12:16:36 ERROR]: Could not pass event AdvancedEntityDeathEvent to AdvancedSpawners v3.5.1
[latest (5).log](https://github.com/GC-spigot/AdvancedSpawners/files/7492756/latest.5.log)
here us server log

**Comment by dinobossytnew** [comment]
Update the plugin.

https://www.spigotmc.org/resources/1-8-1-17-%E2%9C%85-advancedspawners-%E2%9C%85-11x-custom-mobs-%E2%AD%95-create-custom-mobs-in-game-%E2%9A%A1-25-sale-%E2%9A%A1.75458/updates
