### ISSUE TITLE
Item bug for custom drops

### ISSUE THREAD

**Issue by WatchesWolf** [GC-spigot/AdvancedSpawners#316]
Hi
Does anyone know why when i put "TUBE_CORAL" for cod loots it doesn't works BUT! With dirt it works verywell? ^^'
Crimson_fungus too and more.. doesn't work

**Comment by dinobossytnew** [comment]
versión ?

software?

plise log pastebin.com

**Comment by WatchesWolf** [comment]
> 
> 
> versión ?
> 
> software?
> 
> plise log pastebin.com

Last version on Advanced website

Yml ?

I don't have pastebin because it is a custom drop..

**Comment by GC-spigot** [comment]
Fixed
