### ISSUE TITLE
[Issue] Enable issue

### ISSUE THREAD

**Issue by ImYenil** [GC-spigot/AdvancedSpawners#320]
**Describe the bug**
when plugin enable it will error
**To Reproduce**
A way to reproduce the video

**Screenshots / Video**
02.12 06:48:52 [Server] INFO [AdvancedSpawners] Enabling AdvancedSpawners v3.5.9
02.12 06:48:52 [Server] INFO [AdvancedSpawners] Loaded 36,570 custom heads
02.12 06:48:52 [Server] INFO [AdvancedSpawners] Loaded 10 mob configurations.
02.12 06:48:52 [Server] INFO [AdvancedSpawners] Failed to load drops for mob Gorilla: unknown material type RAW_BEEF
02.12 06:48:52 [Server] INFO [AdvancedSpawners] Failed to load drops for mob Monkey: unknown material type INK_SACK
02.12 06:48:52 [Server] INFO [AdvancedSpawners] Could not match material for inventoryLayout.items.0-8
02.12 06:48:52 [Server] INFO [AdvancedSpawners] Could not match material for inventoryLayout.items.18-26
02.12 06:48:52 [Server] INFO [AdvancedSpawners] Could not match material for shopInventory.0-8
02.12 06:48:53 [Server] ERROR Error occurred while enabling AdvancedSpawners v3.5.9 (Is it up to date?)
02.12 06:48:53 [Server] INFO java.lang.IllegalArgumentException: Material cannot be null
02.12 06:48:53 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:86) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:74) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at gcspawners.d.ItemBuilder.<init>(ItemBuilder.java:63) ~[AdvancedSpawners-3.5.9.jar:?]
02.12 06:48:53 [Server] INFO at gcspawners.ItemConfiguration.toItem(ItemConfiguration.java:58) ~[AdvancedSpawners-3.5.9.jar:?]
02.12 06:48:53 [Server] INFO at gcspawners.ShopInventoryHandler.load(ShopInventoryHandler.java:37) ~[AdvancedSpawners-3.5.9.jar:?]
02.12 06:48:53 [Server] INFO at gcspawners.Core.reload(Core.java:324) ~[AdvancedSpawners-3.5.9.jar:?]
02.12 06:48:53 [Server] INFO at gcspawners.Core.onEnable(Core.java:111) ~[AdvancedSpawners-3.5.9.jar:?]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.pinger.management.manager.BasePluginManager.enablePlugin(BasePluginManager.java:258) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at net.pinger.management.inventory.providers.ControllerProvider.lambda$update$2(ControllerProvider.java:194) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at fr.minuskube.inv.ClickableItem.run(ClickableItem.java:26) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at fr.minuskube.inv.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:140) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
02.12 06:48:53 [Server] INFO at fr.minuskube.inv.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:140) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2807) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
02.12 06:48:53 [Server] INFO [AdvancedSpawners] Disabling AdvancedSpawners v3.5.9
02.12 06:48:53 [Server] ERROR Error occurred while disabling AdvancedSpawners v3.5.9 (Is it up to date?)
02.12 06:48:53 [Server] INFO java.lang.NullPointerException: Cannot invoke "gcspawners.AdvancedSpawnerHandler.save(boolean)" because "gcspawners.Core.spawnersHandler" is null
02.12 06:48:53 [Server] INFO at gcspawners.Core.onDisable(Core.java:494) ~[AdvancedSpawners-3.5.9.jar:?]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.pinger.management.manager.BasePluginManager.enablePlugin(BasePluginManager.java:258) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at net.pinger.management.inventory.providers.ControllerProvider.lambda$update$2(ControllerProvider.java:194) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at fr.minuskube.inv.ClickableItem.run(ClickableItem.java:26) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at fr.minuskube.inv.InventoryManager$InvListener.lambda$onInventoryClick$2(InventoryManager.java:140) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
02.12 06:48:53 [Server] INFO at fr.minuskube.inv.InventoryManager$InvListener.onInventoryClick(InventoryManager.java:140) ~[PluginManagerPlus-1.0-SNAPSHOT.jar:?]
02.12 06:48:53 [Server] INFO at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2807) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-391]
02.12 06:48:53 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version [e.g. 6.7.8]
PaperSpigot 1.17.1
version: 3.5.9

**Comment by GC-spigot** [comment]
Fixed
