### ISSUE TITLE
[Issue] Invincible mobs and glitching when hit upon

### ISSUE THREAD

**Issue by GlitchMan-oss** [GC-spigot/AdvancedSpawners#324]
**Describe the bug**
When installed we can’t kill any mob whatsoever. When trying to the mob glitch out but remains. We experimented with turning on off mob stacking and ensured there is no other plugin dedicated to mobs solely. 

Reinstalling plugin didn’t solve the issue affer several reboots. 
It is only when the plugin is not installed that we can kill off mobs again. 
Console gives no exceptional errors either on the occassion. 

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.17.1]
- Plugin Version: latest version

**Comment by GC-spigot** [comment]
Show your plugin list, sounds like incompatibility with something else

**Comment by GlitchMan-oss** [comment]
Currently we are running without it for almost two weeks ... The stackmobs plugin was taken out as it usually collides with plugins that deal with mobs.

Here is an apprehensive list:
AdvancedEnchantments, ajLeaderboards, AuctionHouse, AureliumSkills, Autorank, BattlePass, BuycraftX, ChatControl, ChatItem, ChestShop, Citizens, CitizensGUI, ClearLag, CMILib, CompatNoCheatPlus*, CoreProtect, CosmicVaults, CraftBook, Crates, DeathTP*, DecentHolograms, DeluxeMenus, DiscordSRV, dynmap, Essentials, EssentialsChat, EssentialsSpawn, EvenMoreFish, FastAsyncWorldEdit (WorldEdit), floodgate, Geyser-Spigot, GoldenCrates, GriefPrevention, InvSeePlusPlus, Jobs, KauriVPN, LiteBans, Lottery, LuckPerms, mcMMO, MineableSpawners, Multiverse-Core, MyCommand, NexEngine, NoCheatPlus, PlaceholderAPI, PlayerWarps, ProtocolLib, ProtocolSupport, PvPToggle, SimplePortals, StaffPlus, TabList, TryMe, UberEnchant, UpgradeableHoppers, Vault, ViaVersion, Votifier, VotingPlugin, Vulcan, Wild, WorldGuard

**Comment by GC-spigot** [comment]
Disable `Mob_Healthbar.Enabled` Mob health bar from mcmmo - this is a huge issue and it's likely the cause of this, let me know if it helps
