### ISSUE TITLE
[Issue] Mobs duplicating/un killable 

### ISSUE THREAD

**Issue by SenkoVR** [GC-spigot/AdvancedSpawners#325]
So whenever i kill a mob it instead goes invisible, then duplicates!

**To Reproduce**
just spawn a mob and kill it

**Screenshots / Video**
[If applicable, add screenshots to help explain your problem.](https://gyazo.com/cda71b872c2efa9c56c3c1bf3d8db39b
https://gyazo.com/6e26a86a379056e99dad2d53ca0cd8c3)

**Server Information**
 - Minecraft Version: Paper_Spigot 1.18.1
- Plugin Version: 3.6.3]

Any video request can be sent to me on discord due to my not wanting to leak ip info/console info to the public... 

Discord is: SenkoVR#1000

**Comment by SenkoVR** [comment]
also should state this issue ONLY started after 1.18 drop... no plugins where added since

**Comment by GC-spigot** [comment]
Can you send your plugin list?

**Comment by GC-spigot** [comment]
Disable `Mob_Healthbar.Enabled` Mob health bar from mcmmo - this is a huge issue and it's likely the cause of this

**Comment by SenkoVR** [comment]
AdvancedEnchantments-8.7.24.
  |   | AdvancedNMotd-9.2.0.
  |   | AdvancedSpawners-3.6.2
  |   | Autorank-4.5.1
  |   | BetterSleeping
  |   | CasinoPlugin-4.2.1
  |   | Citizens-2.0.29-b2416
  |   | Clearlag
  |   | DailyRewards-0.7-1.18.1
  |   | EssentialsX-2.19.2
  |   | EssentialsXChat-2.19.2.
  |   | EssentialsXProtect-2.19.0
  |   | EssentialsXSpawn-2.19.2
  |   | ExecutableItems-3.5.8.0
  |   | GriefPrevention 
  |   | HavenCore-0.5.2-1.18.1
  |   | HolographicDisplays
  |   | LuckPerms-Bukkit-5.3.87
  |   | Multiverse-Core-4.3.1
  |   | PlaceholderAPI-2.10.10
  |   | ProtocolLib  
  |   | SCore-1.5.8.1
  |   | Sentinel-2.4.0
  |   | ShopGUIPlus-1.68.1
  |   | SignShop-3.6.1
  |   | SimplePortals-1.6.7
  |   | SpecializedCrates
  |   | Spigot-CommandSigns
  |   | TAB.v3.0.0  
  |   | Vault
  |   | VoidGenerator-1.6.2
  |   | WorldGuardExtraFlags
  |   | floodgate-spigot
  |   | mcMMO
  |   | randomtp-1.5.1-RELEASE
  |   | worldedit-bukkit-7.2.8
  |   | worldguard-bukkit-7.0.6-dist

**Comment by SenkoVR** [comment]
seems it was hp bar thank you
