### ISSUE TITLE
[Issue] texture error and console error

### ISSUE THREAD

**Issue by CREEPERGAMER138** [GC-spigot/AdvancedSpawners#326]
as soon as I start the server I get this error [14:09:57 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

This error is in a newly installed premium server I am on papermc 1.18.1 and I also tested it on papermc 1.17.1 and spigot 1.18 the error is the same and when I select category nothing happens it is all empty and if I give it to select texture 64 does not detect anything

the plugin version is 3.6.4 and I send you photos of the errors in the console
![imagen_2021-12-27_100435](https://user-images.githubusercontent.com/24595466/147483842-dc1b5119-6f67-4023-b462-d27c72de8e90.png)
the first error is when I have my creatures from the past version

![imagen_2021-12-27_102541](https://user-images.githubusercontent.com/24595466/147485452-26b78144-a48f-4197-8319-f99d869c0c9c.png)
![imagen_2021-12-27_102551](https://user-images.githubusercontent.com/24595466/147485475-6dfe801d-535e-4a0f-ace7-6f2c55012a48.png)
![imagen_2021-12-27_102625](https://user-images.githubusercontent.com/24595466/147485507-e4755513-c89c-4153-b7a3-9f2f392dd02c.png)
![imagen_2021-12-27_102639](https://user-images.githubusercontent.com/24595466/147485524-b11b3a71-69aa-4a37-8d8c-e094d19c93db.png)

**Comment by GC-spigot** [comment]
Can you post full server startup log? Would be extremely useful in this case
Send over the `latest.log` file

**Comment by CREEPERGAMER138** [comment]
[1latest.log](https://github.com/GC-spigot/AdvancedSpawners/files/7789631/1latest.log)
[2latest.log](https://github.com/GC-spigot/AdvancedSpawners/files/7789632/2latest.log)
