### ISSUE TITLE
[Issue] Mob Stacking Killing

### ISSUE THREAD

**Issue by HeyOppa** [GC-spigot/AdvancedSpawners#33]
**Describe the bug**
Let's say a x50 cow stacking is there for a while, when we try and kill it, it kills the whole stack instead of one. Only happens if it's been there for a while!

**Server Information:**
 - Minecraft Version **[Paper 1.14.4]**
- Plugin Version **[1.3.1]**

**Comment by GC-spigot** [comment]
This can only happen through server restarts since mob internal data does not save
