### ISSUE TITLE
[Issue] Message Error

### ISSUE THREAD

**Issue by flan202** [GC-spigot/AdvancedSpawners#330]
[10:32:46] [Server thread/ERROR]: [AdvancedSpawners] Unable to retreive connection
--
409 | java.sql.SQLException: Values not bound to statement
410 | at org.sqlite.core.CorePreparedStatement.checkParameters(CorePreparedStatement.java:64) ~[patched_1.12.2.jar:git-Paper-1619]
411 | at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:73) ~[patched_1.12.2.jar:git-Paper-1619]
412 | at gcspawners.SqlDatabase.initialize(SqlDatabase.java:32) ~[?:?]
413 | at gcspawners.SqlDataHandler.load(SqlDataHandler.java:69) ~[?:?]
414 | at gcspawners.Core.onEnable(Core.java:104) ~[?:?]
415 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1619]
416 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1619]
417 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1619]
418 | at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1619]
419 | at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1619]
420 | at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1619]
421 | at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1619]
422 | at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1619]
423 | at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1619]
424 | at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1619]
425 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

Server version: 1.12.2
Plugin version: Last one

**Comment by GC-spigot** [comment]
Does restarting fix this or does this happen every time?

**Comment by GC-spigot** [comment]
Nevermind, fixed
