### ISSUE TITLE
[Issue] Weird stacked mob behavior

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedSpawners#332]
**Describe the bug**
When killing a stacked mob, they juust multiply, unstacked, and they attack me. I have AI disabled and knockback disabled, but why is knockback still there?

**To Reproduce**
Use 1.12.2 Paper, then killing stacked mobs.

**Screenshots / Video**
https://youtu.be/2Itxdyvd0e4

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.12.2
- Plugin Version [05:53:26 INFO]: [<] +-----< AdvancedSpawners [v3.6.8] >-----+ [>]

**Comment by GC-spigot** [comment]
Please let me know now if it's resolved in 3.6.10

**Comment by GC-spigot** [comment]
Fixed
