### ISSUE TITLE
[Issue] STACK GUI running TWICE.

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedSpawners#333]
**Describe the bug**
Running twice, it doubles. 

**To Reproduce**
Check video.

**Screenshots / Video**
https://youtu.be/K_zv-sS4N_o

**Server Information (please complete the following information):**
 - Minecraft Version PaperSpigot 1.12.2
- Plugin Version 3.6.8

**Comment by GC-spigot** [comment]
So this is caused by `/as reload` causing GUIs to be reactivated multiple times, fixed for next update
