### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by DanielBratee** [GC-spigot/AdvancedSpawners#334]
I have LaggAssist plugin, and AdvancedSpawners, and player is trying to kill mob, but for some reason, like last hit to kill mob mob dissapear and drops nothing. i unload AdvancedSpawners plugin using PlugManX everything is great, i load Spawners, unload LaggAssist, everything is great again, but when are both load its has like some confilict i dont get it.
**Server Information (please complete the following information):**
 - Minecraft Version: git-Purur-1547 (MC: 1.18.1)
- Plugin Version v3.6.8

**Comment by GC-spigot** [comment]
Fixed
