### ISSUE TITLE
Spawnershop allowing negative purchasing[Issue]

### ISSUE THREAD

**Issue by lvp12345** [GC-spigot/AdvancedSpawners#338]
**Describe the bug**
When a player goes to purchase from /spawnershop, its allowing them to buy it and bypass their current balance, in turn making it so they can go negative. There is no option in the eco config for allowing negative purchasing and also doesn't allow such from any of our other eco stuff.

**To Reproduce**
Using EconomyPlus, and AdvancedSpawners (latest)

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version Spigot build 3434, 1.18.1-R0.1-Snapshot
- Plugin Version 3.8 economyplus, AdvancedSpawners 3.6.16

**Comment by GC-spigot** [comment]
Fixed
