### ISSUE TITLE
Mobs bug damage

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedSpawners#339]
Bug:
Damaging zombies / zombified piglins with Smite 5 does not insta kill, Happens often actually, but when doing /aspawners killall the issue gets fixed, but it will happen again eventually, it happens randomly. why?

Server Version:
[21:37:12 INFO]: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

Debug:
https://pastebin.com/Fn2hiUQJ

Video:
https://www.youtube.com/watch?v=vROSA76bOCg

**Comment by illudota** [comment]
here is another confirmation:
https://discord.com/channels/376425582139015168/685731142334283829/947395829830909972
VIDEO IN DISCORD
I used smite 255 and sharpness 255, they get one shot, but when i use smite 5, or either sharp 5 thye dont.
sometimes the damage outputs are really broken.

**Comment by GC-spigot** [comment]
Replied on discord
