### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by ZeroTwoO2** [GC-spigot/AdvancedSpawners#340]
**Describe the bug**
When i start the server it says it couldn't find MCMMO

**To Reproduce**
Just put the plugin on a 1.18 server

**Screenshots / Video**
I can't add a screenshot but i think a pastebin is better https://www.toptal.com/developers/hastebin/werecoyahu.css

**Server Information (please complete the following information):**
 - Minecraft Version 1.18.1 Purpur
- Plugin Version 3.5.1

**Comment by GC-spigot** [comment]
Fixed next update
