### ISSUE TITLE
Mob damage error?

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedSpawners#344]
Hello, i had an error in my console in the latest update, this is the first time i got this, maybe this might be related to the error i reported before? https://github.com/GC-spigot/AdvancedSpawners/issues/339

here's the error, it spammed my console, must be it happens everytime a player attacks / hits a mob since i got afk grinders in my server.
https://pastebin.com/c9A3wrGx

**Comment by illudota** [comment]
https://github.com/GC-spigot/AdvancedSpawners/issues/339 
Might be related? this bug is really destroying my server and destroying grinding experience.

**Comment by illudota** [comment]
EDIT: This happens when player damages another player! not mob! my bad!

**Comment by GC-spigot** [comment]
Fixed
