### ISSUE TITLE
Console Error [Issue]

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedSpawners#345]
**Describe the bug**
Everytime a player hits another player, this error occurs on console

**To Reproduce**
Hit a player.

**Screenshots / Video**
Here it shows that players pvping, then the error spams, notice when they stop hitting each other the error stops, but when they started to attack each other again, it occurs again.
https://www.youtube.com/watch?v=i8_a4VSeaIs

Error line:
https://pastebin.com/vAd6ZnWQ

**Server Information (please complete the following information):**
- Minecraft Version: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Plugin Version: 3.7.3

NOTE: I Reported this issue before:
https://github.com/GC-spigot/AdvancedSpawners/issues/344

but it's a wrong one, it does not occur on mob damage but it occurs when a player damages another player instead.

**Comment by GC-spigot** [comment]
Fixed
