### ISSUE TITLE
Crash Error Is Back [Issue]

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedSpawners#347]
**Describe the bug**
Hello, Saving error crash is back again

**To Reproduce**
none. just a saving error

**Screenshots / Video**
https://pastebin.com/yaM75aEu

**Server Information (please complete the following information):**
Minecraft Version: This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugin Version: 3.7.3

**Comment by GC-spigot** [comment]
Fixed
