### ISSUE TITLE
Console Error Again [Issue]

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedSpawners#348]
**Describe the bug**

**To Reproduce**
Idk how, it just spammed my console for a bit, tried attacking players or mob, didnt show up, but yeah it shows up on my console sometimes, wonder what it is? but for sure it must be related to some damage

**Screenshots / Video**
I only have the lines:
https://pastebin.com/hyxeaag2

This one too, damage error but different lines:
https://pastebin.com/8icABxjd

**Server Information (please complete the following information):**
 - 1.16.5 PaperSpigot
- 3.7.4

**Comment by GC-spigot** [comment]
Issues with Tipped Arrows, will be resolved next update
