### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by FlintlockKatze** [GC-spigot/AdvancedSpawners#349]
**Describe the bug**
Magma cubes and slimes when they take damage from potions such as harming or acid water, will multiply into hundreds of many sized mobs of them selves

**To Reproduce**
A way to reproduce the video
I cannot reproduce it as it literately crashes my server
*We have done more testing very carefully, it seems when they are also stuck in a wall they end up multiplying very fast that way as well. [https://youtu.be/0GHAUVYjiac ](url)

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.17.1]
- Plugin Version [e.g. 3.7.4]

**Comment by GC-spigot** [comment]
Fixed
