### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by ivandelp** [GC-spigot/AdvancedSpawners#35]
**Describe the bug**
Plugin are not loading to start the server.

**To Reproduce**
-

**Screenshots / Video**
https://pastebin.com/nDqeNdZ2

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [1.3.3]

**Comment by GC-spigot** [comment]
Fixed in new versions
