### ISSUE TITLE
[Issue] /as give

### ISSUE THREAD

**Issue by ivandelp** [GC-spigot/AdvancedSpawners#39]
**Describe the bug**
If you add a name of a mob that it's not created by that name, you give an error in chat and console, I reported that to solve that and get better the plugin.

I try that with the command /as give

**To Reproduce**
/as give PlayerName NoMobCreatedWithThatName

**Screenshots / Video**
https://pastebin.com/ntWLHCqk

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [1.4.3]

**Comment by GC-spigot** [comment]
Fixed
