### ISSUE TITLE
[Issue] Chance Drops

### ISSUE THREAD

**Issue by ivandelp** [GC-spigot/AdvancedSpawners#40]
**Describe the bug**
I change the name of the files of a mob and chance of give the items are not correct.

**To Reproduce**
-

**Screenshots / Video**
Gorilla for example give me often quartz  and the chance it's of 2.

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [1.4.3]

**Comment by GC-spigot** [comment]
Fixed
