### ISSUE TITLE
[Issue]Sound and Health problem

### ISSUE THREAD

**Issue by ivandelp** [GC-spigot/AdvancedSpawners#42]
**Describe the bug**
I set a sound of the link in config of the mob and set the default word but not work and no make a sound.

And the health are not set it correctly, I stopped the server but not works, I set 200 for example and with 2 clicks of sword, I kill that mob.

Previously I change the name of the file.

**To Reproduce**
-

**Screenshots / Video**
These two parameters:  https://imgur.com/a/gzxYzp2

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [1.4.3]

**Comment by GC-spigot** [comment]
Fixed
