### ISSUE TITLE
[Issue] Turtle Mob

### ISSUE THREAD

**Issue by ivandelp** [GC-spigot/AdvancedSpawners#43]
**Describe the bug**
Legs of turtle mob are bugged in the ground.

**To Reproduce**
-

**Screenshots / Video**
https://imgur.com/a/E6GBgV6

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [1.4.5]

**Comment by kacperleague9** [comment]
For me they dont spawn
