### ISSUE TITLE
[Issue] Turtle is not working

### ISSUE THREAD

**Issue by kacperleague9** [GC-spigot/AdvancedSpawners#47]
**Describe the bug**

The bug is that turtle doesnt spawn. 1.12.2

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8] PaperSpigot 1.12.2
- Plugin Version [e.g. 6.7.8] 1.4.7

**Comment by GC-spigot** [comment]
It's spawner needs darkness + grass
