### ISSUE TITLE
[Request] Head/Block display in spawner

### ISSUE THREAD

**Issue by kacperleague9** [GC-spigot/AdvancedSpawners#48]
** Describe the Request**

My suggestion is that you can put a head or block inside a spawner while placed to show players what mob will spawn. [like in epicspawners]

**Comment by kacperleague9** [comment]
Any news about it?

**Comment by kacperleague9** [comment]
Still waiting for it

**Comment by kacperleague9** [comment]
Still

**Comment by Endphoenix** [comment]
Yes this Feature would be so good!

**Comment by kacperleague9** [comment]
And drill
