### ISSUE TITLE
[Request] Breeding&nametags&set mob type

### ISSUE THREAD

**Issue by Yoloman0013** [GC-spigot/AdvancedSpawners#51]
With custom item set in special config breed custom animals
And allow to use nametags on custom mobs 
In config allow to set for each mob its type like Friendly, predator and maybe scared? which runs away from player

**Comment by GC-spigot** [comment]
I'll see what I can do, but name tags can't really be done since stacking will just remove them & types for mobs are just limited to what vanilla has to offer with Silverfish as I'm using that mob's AI
