### ISSUE TITLE
[Request] Placeholder for AdvancedSpawners

### ISSUE THREAD

**Issue by Jok3rTV** [GC-spigot/AdvancedSpawners#54]
I would like to have a placeholder that will show the spawner drops on spawnerDisplays: 

      - ''
      - ' &f&l* &c&lSPAWNER TYPE: &7%spawner type%'
      - ' &f&l* &c&lDROPS: &7%spawner drop%'
      - ''

for example

**Comment by GC-spigot** [comment]
What do you want it to show in drops? whole entire list of dropped materials?
