### ISSUE TITLE
[Issue] Players can kill animals from other even it is protected

### ISSUE THREAD

**Issue by makemp1997** [GC-spigot/AdvancedSpawners#56]
**Describe the bug**

**To Reproduce**
See **Server Information (please complete the following information):** 

**Screenshots / Video**
Sadly I didn't recorded it because I didn't know at first what caused it

**Server Information (please complete the following information):**
 - PaperSpigot 1.15.2
- Plugin Version 1.7.1

I got some complaint from players that they could kill animals of other players while visiting. At first I didn't know what cuased it so I asked first on the Discord from Bentobox, someone there suggested it that it an other plugin. So test it on my computer and did the following:

1. removing every plugin except BentoBox and VoidGenerator
2. Start the server
3. enter the server 
4. test it, found out that the animals as it should was protected
5. Close the server
6. Adding Worldguard and Worldedit, since I know this also might causing some issues
7 . Starting the server
8. reenter the server
9. Re-test it again and found out that the animals also was protected
10. I did step 5 until  9, since I found out that plugins wasn't causing it, until I was AdvancedSpawners

Site note: I did from back to forth, because I thought the issue was coming from WorldGuard

11. Close the server
12. adding AdvancedSpawners
13. Start the server
14. retest it and found out that I could hurting animals, but getting a message that it was protected
15. Close the server
16. update and remove the config of AdvancedSpawners
17. start the server for the final time
18. Reenter and test it again, found out still the same issue
19. Check the config AdvancedSpawners, to find any settings what might causing it but at least I didn't find it

So question it there a setting what might cause this issues?

Note: The attached file is a schreenshot from my updadted plugins, also I had to remove AdvancedSpawners until this issue have been solved. 

![Screenshot_2](https://user-images.githubusercontent.com/22965328/81174014-506c4180-8fa1-11ea-9864-647ca1d45548.png)

Greetings,

makemp1997
aka makemp2014

**Comment by GC-spigot** [comment]
Fixed
