### ISSUE TITLE
[Issue] Fire Aspect/Sweeping Edge not functioning after installation

### ISSUE THREAD

**Issue by Xaitin** [GC-spigot/AdvancedSpawners#59]
**Describe the bug**
Fire Aspect/Sweeping Edge no longer functions after mod installation. Tested using cows that existed before the mod, fire aspect worked, bred the cows and the calves that popped out had the new mob stacking tag and were immune to fire aspect/sweeping edge.

**To Reproduce**
Enchant a sword with fire aspect and smack wild mobs. They won't catch on fire. Swing while the + critical indicator is lit up, you won't cleave multiple mobs.
**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 208]
- Plugin Version [1.7.3]

**Comment by GC-spigot** [comment]
Sweeping edge works a bit different - it kills multiple in the stack rather than hitting in radius mobs. Added fire aspect support.
