### ISSUE TITLE
Only owner and staff can see hologram

### ISSUE THREAD

**Issue by PurgeTaxMC** [GC-spigot/AdvancedSpawners#6]
My server has a purge day twice a month, and players raid other players.  With the stacking mobs and spawners, is it possible to make it so only the owner of the spawners and staff with the permission can see it as well? That way it doesnt reveal underground base locations?

**Comment by PurgeTaxMC** [comment]
Just to add to this, I meant the names above the spawners, they show to all players through the ground, which I want only the owner of the spawner and the staff with set permission to be able to see the names

**Comment by GC-spigot** [comment]
Added a bit different set up - https://github.com/GC-spigot/AdvancedSpawners/commit/978a17c56aebc38054d3213bf2f35cff4c86e6f1#diff-0f1be8eec416e71c28b41efb0544df26R65-R69
