### ISSUE TITLE
[Issue] Players still can kill animals from other even it is protected 

### ISSUE THREAD

**Issue by makemp1997** [GC-spigot/AdvancedSpawners#62]
**Describe the bug**
Players can kill protected animals

**To Reproduce**
see: https://github.com/GC-spigot/AdvancedSpawners/issues/56

**Screenshots / Video**
https://youtu.be/F-89bu983kY

**Server Information (please complete the following information):**

- PaperSpigot 1.15.2
- Plugin Version 1.7.3

I want to inform you that it is sadly still possible to kill protected animals, see https://github.com/GC-spigot/AdvancedSpawners/issues/56

Update: I forgot to mention that I had test it first on my computer and also I had removed every plugin except AdvanchedSpawner, bentobox, Protocolib and voidgenerator, als I had removed the addon ExtraMods from BentoBox. Even then sadly the issue remains

**Comment by GC-spigot** [comment]
Okay should be now fixed with this as well!
