### ISSUE TITLE
[Request] Universal Placeholders for Lore and Spawner

### ISSUE THREAD

**Issue by coopersully** [GC-spigot/AdvancedSpawners#67]
I'm not too sure if this is a bug or simply a feature, but it would be very neat if the placeholders, such as %level% were also usable in the spawner's name in the config.yml, similar to below:

`  spawnersDisplay:
    # Spawner Item Name
    name: '&e%spawner type% Spawner &7(Level %level)'

    # Spawner Item Lore
    lore:
      - ''

    # Should spawner item be glowing?
    glowing: false`

Personally, this would help me make it a simple item with minimal interaction to understand and I think it'd be a great little addition. :)

**Comment by GC-spigot** [comment]
Added
