### ISSUE TITLE
Changing spawning conditions of any spawners

### ISSUE THREAD

**Issue by colinquaden** [GC-spigot/AdvancedSpawners#69]
Hello,

For some spawners i want the mobs to spawn in the air because otherwise the spawner must touch the ground for the mobs to spawn. for example a blaze, ghast, mobgrinder and igs farms that would be verry helpfull because they just spawn in the air and fall in the grinder.

Also make it so you can disable aggressiveness for certain mobs

can this be added?

thanks

Colin Quaden

**Comment by GC-spigot** [comment]
You'd need to change the spawner type to those mobs' types, my plugin works depending on specific set spawner conditions
