### ISSUE TITLE
change lvlup pricing

### ISSUE THREAD

**Issue by colinquaden** [GC-spigot/AdvancedSpawners#70]
Hello,

Would it be possible to create something so we can change pricing of upgrades for each spawner?

for example Iron Golem cost 50k for first 100k for second and so on,

and pig spawners should be 10k for the first 20k for the second and so on

we cannot change the pricing right now for every spawner and that would make useless spawners more usefull because upgrading will be cheaper.

thanks :)

Colin Quaden

**Comment by GC-spigot** [comment]
Added
