### ISSUE TITLE
[Issue]The Plugin Turns Vanilla Spawners Into Pig Spawners

### ISSUE THREAD

**Issue by xWolfArmy** [GC-spigot/AdvancedSpawners#71]
So when I bought and installed the plugin into my server and it stopped my vanilla/custom spawners from turning into their specified spawner type. So I place down an iron golem spawner and then it turns into a pig spawner. The spawners from the advanced spawners plugin works perfectly but it just stops my normal spawners from working. Is there a way to fix this? Please help.

**Server Information (please complete the following information):**
 - Minecraft Version [Spigot1.15.2]
- Plugin Version [1.8.6](The Latest)

**Comment by GC-spigot** [comment]
Give spawners to yourself / players using /as give command. It supports vanilla mobs.
