### ISSUE TITLE
Big bug

### ISSUE THREAD

**Issue by Unspecified13** [GC-spigot/AdvancedSpawners#72]
**Describe the bug**
Hello i report today 2 beug first one is a problem with eggs like creeper , i have spam the spawn off creeper with eggs and sometimes a custom mobs like a monkey or a turtle spawn (normaly a creeper spawn ) i have think it's because i spam so i have try it one more time on juste spawning 1 creeper (30 block off distancebetween them) after 6 creeper spawn a turtle have spawn, it's a big problem because iff my player try to breack a chest in a enemy home with a creeper and a turtle spawn they are not to be happy ;) 

second problem =, upgrade system don't work i have create a mob spawner level 5 and i have set it and i have set also a spawner level 1 i have wait 5 minute and i have look, we have the same number off mobs so normaly the spawner level 5 need to spawn x3 x4 more mobs no ? (spawner level1 have spawn 22 mobs and level 5 20 mobs look the picture) 

and juste a feature request also : a pickaxe to take the custom spawner when we have place it ? 

**Screenshots / Video**

![2020-05-15_14 21 07](https://user-images.githubusercontent.com/62668152/82050210-0594ad00-96b8-11ea-918b-f1c18facd59e.png)
![2020-05-14_15 44 27](https://user-images.githubusercontent.com/62668152/82050292-2f4dd400-96b8-11ea-93aa-553b14d563b3.png)
![2020-05-14_15 44 32](https://user-images.githubusercontent.com/62668152/82050303-3379f180-96b8-11ea-8553-aa32a2c08d08.png)

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. ISpigot 1.8.8]
- Plugin Version [e.g. 1.8.7]

**Comment by GC-spigot** [comment]
Fixed
