### ISSUE TITLE
[Issue] Spawners not stacking properly

### ISSUE THREAD

**Issue by Aarpn** [GC-spigot/AdvancedSpawners#77]
**Describe the bug**
If I place irongolem onto irongolems they dont stack, it takes the spawner etc, just says placed spawner x1 but if I break 1 it is just 1 not multiple

**To Reproduce**
use latest wildstacker and place a vanilla mob like irongolem onto another irongolem spawner
![2020-05-19_22 33 28](https://user-images.githubusercontent.com/61875315/82380740-e0d66780-9a20-11ea-8c1b-e27c004b3c8e.png)

**Server Information (please complete the following information):**
 - PaperSpigot 1.8.8
- Plugin Version 1.9.7

**Comment by GC-spigot** [comment]
Fixed
