### ISSUE TITLE
Many little bug

### ISSUE THREAD

**Issue by Unspecified13** [GC-spigot/AdvancedSpawners#84]
**Describe the bug**
I found a weed with the mob stacking: 
for example : there's a stack of 60 mobs and if you hit them it dies 1 by 1 so everything's ok but if you hit them and make them die from a fall all the mobs die at once ( the 60 mobs die) which is a problem 

2nd point, the creeper stacks up I couldn't find a way to cancel it because during a plunder it's a problem. 

You told me that you would add for the silk touch to pick up the spawners a system to limit to 5 spawners max for example the number that could be picked up with 1 pick. 

last thing I have a problem spawning the mobs on my server don't spawn it it shows up and then disappears 

https://gyazo.com/709793a5001950fd2437fe6fc8b74ef5 

no error in consol

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]
- Plugin Version last version

**Comment by GC-spigot** [comment]
1st - https://prnt.sc/spw7k7
2nd - I don't understand
3rd - Ill look into levels system
4th - Make sure that area is allowed to have mobs - seems like worldguard or somethign like that might be causing it, will look into it

**Comment by Unspecified13** [comment]
the area is ok for the spawn off the mob men (i don't have worldguard) 

for the second point to be simple : can you add the possibility for use to say i don't want mobs creeper can stack together
