### ISSUE TITLE
[Issue] Plugin Not Loading

### ISSUE THREAD

**Issue by ArchieWasTaken** [GC-spigot/AdvancedSpawners#87]
**Describe the bug**
Plugin not loading.

**To Reproduce**
Not entirely sure.

**Screenshots / Video**
https://hastebin.com/icitahuloh.css

**Server Information (please complete the following information):**
 - Minecraft Version: Voltane 1.8.8
- Plugin Version: Latest as of Now [2.0.13]
--

**Comment by GC-spigot** [comment]
Fixed
