### ISSUE TITLE
[Issue] Armorstands preventing chunk save?

### ISSUE THREAD

**Issue by Exillium313** [GC-spigot/AdvancedSpawners#9]
After the first time I spawned each mob from /as spawnCustomMob, I got timed out, when I came back I killed them all and then everytime my world saves I see this message: EntityArmorStand[''/9294, uuid='c825a4d2-e692-4434-98ed-8e01a54bc49a', l='world', x=-63.52, y=63.00, z=320.29, cx=-4, cz=20, tl=1459, v=false, d=true] is not in this chunk, skipping save. This a bug fix to a vanilla bug. Do not report this to PaperMC please.

Attempt the above? Only other thing is I am currently used WorldBorder to fill the world, which is why I have frequent world saves, everytime it saves I see this message 3 times over with just slight variations of the coordinates.

Not really relevant, as I tp'd to the coordinates there is nothing there, no armorstands I can edit, attempted to butcher all armorstands in radius, nothing worked.

 - Paper 1.15.2
- Plugin Version 1.1.4

**Comment by GC-spigot** [comment]
Try `/killall named` if you're using Essentials or `/minecraft:kill @e` to kill all entities in the world
