### ISSUE TITLE
[Issue] Natural mobs don't die

### ISSUE THREAD

**Issue by megamineservidores** [GC-spigot/AdvancedSpawners#90]
When natural mobs are generated and grouped, when they kill they don't die, they are grouped forever and always dropping the drops.

649 mobs and when i kill 1 for 1 it is not updating no https://media.discordapp.net/attachments/720764153949716510/720767538367168523/unknown.png

I'm using a sword with 100 enchantments and it's killing infinitely 32 cows
https://media.discordapp.net/attachments/717462081904967745/720759251353731183/unknown.png?width=512&height=629

Minecraft Server 1.15.2
Plugin: Version Recent

**Comment by GC-spigot** [comment]
What other plugins do you have for mob stacking?

**Comment by megamineservidores** [comment]
I use advancedspawners only

**Comment by GC-spigot** [comment]
Works fine on my test server, what plugins are you using?

**Comment by megamineservidores** [comment]
i am using the plugins https://prnt.sc/sz8lm5

**Comment by megamineservidores** [comment]
I'm waiting for an answer

**Comment by GC-spigot** [comment]
I'm unable to recreate this, please add me on discord GC#0830 so we can test this out

**Comment by megamineservidores** [comment]
answer me on discord! Paullo#0330

**Comment by megamineservidores** [comment]
I need support, I paid for the product and I don't have support.
He asked me to call discord and he didn't answer me, so it's difficult and I have a commitment to my players.
![spawners](https://user-images.githubusercontent.com/25700412/84941984-8cbeb180-b0b8-11ea-8910-e5dfd6d6b5d7.png)
