### ISSUE TITLE
[Request] ItemStacker

### ISSUE THREAD

**Issue by LeCraft2Ouf** [GC-spigot/AdvancedSpawners#96]
Hello, 

Since the plugin contains a MobStacker, why not also put an ItemStacker? It seems more logical... It was a simple idea.

Sincerely

**Comment by GC-spigot** [comment]
The mob stacker is forced because custom mobs otherwise would never be able to stack. Since this is 'advancedspawners' plugin it's only logical as well to have mob stacking feature, but not item stacking.
