### ISSUE TITLE
[Issue]Slimes duplicates in a higher rate than default

### ISSUE THREAD

**Issue by MagnusMelbye** [GC-spigot/AdvancedSpawners#99]
When a player kills a slime, it duplicates into bigger or smaller slimes. Since it dosent follow the default patterns (Dublicates into smaller slimes), it will eventually cause unlimited amount of Slimes.

[https://gyazo.com/ec73f6e2fe765e71637b691efc8e8220](url)
[https://gyazo.com/b555a5e1ce0d3014882e690cd5a07245](url)

Minecraft Version [Paperspigot 1.15.2]
Plugin Version [2.2.2]

**Comment by GC-spigot** [comment]
Thanks will be looking into this
